using System;
using System.Text;
using System.Data;
using System.Collections;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;

/*This class is autogenerated by Khedrawy Code gen v.3.1*/
namespace Forwarding.MvcApp.Models.ContainerFreightStation.Transactions
{
    [Serializable]
    public class CPKWH_CntrStock
    {
        #region "variables"
        private Int32 mID;
        #endregion

        #region "Methods"
        public Int32 ID
        {
            get { return mID; }
            set { mID = value; }
        }
        #endregion
    }
    [Serializable]
    public partial class CVarWH_CntrStock : CPKWH_CntrStock
    {
        #region "variables"
        internal Boolean mIsChanges = false;
        internal String mContainerNumber;
        internal Int32 mContainerTypesID;
        internal Boolean misOwn;
        internal Int32 mWH_WarehouseID;
        #endregion

        #region "Methods"
        public String ContainerNumber
        {
            get { return mContainerNumber; }
            set { mIsChanges = true; mContainerNumber = value; }
        }
        public Int32 ContainerTypesID
        {
            get { return mContainerTypesID; }
            set { mIsChanges = true; mContainerTypesID = value; }
        }
        public Boolean isOwn
        {
            get { return misOwn; }
            set { mIsChanges = true; misOwn = value; }
        }
        public Int32 WH_WarehouseID
        {
            get { return mWH_WarehouseID; }
            set { mIsChanges = true; mWH_WarehouseID = value; }
        }
        #endregion

        #region Functions
        public Boolean GetIsChange()
        {
            return mIsChanges;
        }
        public void SetIsChange(Boolean IsChange)
        {
            mIsChanges = IsChange;
        }
        #endregion
    }

    public partial class CWH_CntrStock
    {
        #region "variables"
        /*If "App.Config" isnot exist add it to your Application
		Add this code after <Configuration> tag
		-------------------------------------------------------
		<appsettings>
		<add key="ConnectionString" value="............"/>
		</appsettings>
		-------------------------------------------------------
		where ".........." is connection string to database server*/
        private SqlTransaction tr;
        public List<CVarWH_CntrStock> lstCVarWH_CntrStock = new List<CVarWH_CntrStock>();
        public List<CPKWH_CntrStock> lstDeletedCPKWH_CntrStock = new List<CPKWH_CntrStock>();
        #endregion

        #region "Select Methods"
        public Exception GetList(string WhereClause)
        {
            return DataFill(WhereClause, true);
        }
        public Exception GetListPaging(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotalRecords)
        {
            return DataFill(PageSize, PageNumber, WhereClause, OrderBy, out TotalRecords);
        }
        public Exception GetItem(Int32 ID)
        {
            return DataFill(Convert.ToString(ID), false);
        }
        private Exception DataFill(string Param, Boolean IsList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarWH_CntrStock.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                if (IsList == true)
                {
                    Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                    Com.CommandText = "[dbo].GetListWH_CntrStock";
                    Com.Parameters[0].Value = Param;
                }
                else
                {
                    Com.CommandText = "[dbo].GetItemWH_CntrStock";
                    Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int));
                    Com.Parameters[0].Value = Convert.ToInt32(Param);
                }
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarWH_CntrStock ObjCVarWH_CntrStock = new CVarWH_CntrStock();
                        ObjCVarWH_CntrStock.ID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarWH_CntrStock.mContainerNumber = Convert.ToString(dr["ContainerNumber"].ToString());
                        ObjCVarWH_CntrStock.mContainerTypesID = Convert.ToInt32(dr["ContainerTypesID"].ToString());
                        ObjCVarWH_CntrStock.misOwn = Convert.ToBoolean(dr["isOwn"].ToString());
                        ObjCVarWH_CntrStock.mWH_WarehouseID = Convert.ToInt32(dr["WH_WarehouseID"].ToString());
                        lstCVarWH_CntrStock.Add(ObjCVarWH_CntrStock);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        private Exception DataFill(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotRecs)
        {
            Exception Exp = null;
            TotRecs = 0;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarWH_CntrStock.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                Com.Parameters.Add(new SqlParameter("@PageSize", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@PageNumber", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                Com.Parameters.Add(new SqlParameter("@OrderBy", SqlDbType.VarChar));
                Com.CommandText = "[dbo].GetListPagingWH_CntrStock";
                Com.Parameters[0].Value = PageSize;
                Com.Parameters[1].Value = PageNumber;
                Com.Parameters[2].Value = WhereClause;
                Com.Parameters[3].Value = OrderBy;
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarWH_CntrStock ObjCVarWH_CntrStock = new CVarWH_CntrStock();
                        ObjCVarWH_CntrStock.ID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarWH_CntrStock.mContainerNumber = Convert.ToString(dr["ContainerNumber"].ToString());
                        ObjCVarWH_CntrStock.mContainerTypesID = Convert.ToInt32(dr["ContainerTypesID"].ToString());
                        ObjCVarWH_CntrStock.misOwn = Convert.ToBoolean(dr["isOwn"].ToString());
                        ObjCVarWH_CntrStock.mWH_WarehouseID = Convert.ToInt32(dr["WH_WarehouseID"].ToString());
                        TotRecs = Convert.ToInt32(dr["TotalRecords"].ToString());
                        lstCVarWH_CntrStock.Add(ObjCVarWH_CntrStock);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
        #region "Common Methods"
        private void BeginTrans(SqlCommand Com, SqlConnection Con)
        {

            tr = Con.BeginTransaction(IsolationLevel.Serializable);
            Com.CommandType = CommandType.StoredProcedure;
        }

        private void EndTrans(SqlCommand Com, SqlConnection Con)
        {

            Com.Transaction = tr;
            Com.Connection = Con;
            Com.ExecuteNonQuery();
            tr.Commit();
        }

        #endregion
        #region "Set List Method"
        private Exception SetList(string WhereClause, Boolean IsDelete)
        {

            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                if (IsDelete == true)
                    Com.CommandText = "[dbo].DeleteListWH_CntrStock";
                else
                    Com.CommandText = "[dbo].UpdateListWH_CntrStock";
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                BeginTrans(Com, Con);
                Com.Parameters[0].Value = WhereClause;
                EndTrans(Com, Con);
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
        #region "Delete Methods"
        public Exception DeleteItem(List<CPKWH_CntrStock> DeleteList)
        {

            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                Com.CommandText = "[dbo].DeleteItemWH_CntrStock";
                Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int));
                foreach (CPKWH_CntrStock ObjCPKWH_CntrStock in DeleteList)
                {
                    BeginTrans(Com, Con);
                    Com.Parameters[0].Value = Convert.ToInt32(ObjCPKWH_CntrStock.ID);
                    EndTrans(Com, Con);
                }
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
                DeleteList.Clear();
            }
            return Exp;
        }

        public Exception DeleteList(string WhereClause)
        {

            return SetList(WhereClause, true);
        }

        #endregion
        #region "Save Methods"
        public Exception SaveMethod(List<CVarWH_CntrStock> SaveList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                Com.Parameters.Add(new SqlParameter("@ContainerNumber", SqlDbType.NVarChar));
                Com.Parameters.Add(new SqlParameter("@ContainerTypesID", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@isOwn", SqlDbType.Bit));
                Com.Parameters.Add(new SqlParameter("@WH_WarehouseID", SqlDbType.Int));
                SqlParameter paraID = Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, "ID", DataRowVersion.Default, null));
                foreach (CVarWH_CntrStock ObjCVarWH_CntrStock in SaveList)
                {
                    if (ObjCVarWH_CntrStock.mIsChanges == true)
                    {
                        if (ObjCVarWH_CntrStock.ID == 0)
                        {
                            Com.CommandText = "[dbo].InsertItemWH_CntrStock";
                            paraID.Direction = ParameterDirection.Output;
                        }
                        else if (ObjCVarWH_CntrStock.ID != 0)
                        {
                            Com.CommandText = "[dbo].UpdateItemWH_CntrStock";
                            paraID.Direction = ParameterDirection.Input;
                        }
                        BeginTrans(Com, Con);
                        if (ObjCVarWH_CntrStock.ID != 0)
                        {
                            Com.Parameters["@ID"].Value = ObjCVarWH_CntrStock.ID;
                        }
                        Com.Parameters["@ContainerNumber"].Value = ObjCVarWH_CntrStock.ContainerNumber;
                        Com.Parameters["@ContainerTypesID"].Value = ObjCVarWH_CntrStock.ContainerTypesID;
                        Com.Parameters["@isOwn"].Value = ObjCVarWH_CntrStock.isOwn;
                        Com.Parameters["@WH_WarehouseID"].Value = ObjCVarWH_CntrStock.WH_WarehouseID;
                        EndTrans(Com, Con);
                        if (ObjCVarWH_CntrStock.ID == 0)
                        {
                            ObjCVarWH_CntrStock.ID = Convert.ToInt32(Com.Parameters["@ID"].Value);
                        }
                        ObjCVarWH_CntrStock.mIsChanges = false;
                    }
                }
            }
            catch (Exception ex)
            {
                Exp = ex;
                if (tr != null)
                    tr.Rollback();
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }
        #endregion
        #region "Update Methods"
        public Exception UpdateList(string UpdateClause)
        {

            return SetList(UpdateClause, false);
        }

        #endregion
    }
}
