//GetListvwInvoices make Varchar
//Com.CommandTimeout = 3000;

using System;
using System.Text;
using System.Data;
using System.Collections;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;

/*This class is autogenerated by Khedrawy Code gen v.3.1*/
namespace Forwarding.MvcApp.Models.Operations.Operations.Generated
{
    [Serializable]
    public partial class CVarvwInvoices
    {
        #region "variables"
        internal Boolean mIsChanges = false;
        internal Int64 mID;
        internal Int64 mInvoiceNumber;
        internal Int32 mInvoiceTypeID;
        internal String mInvoiceTypeCode;
        internal String mInvoiceTypeName;
        internal String mConcatenatedInvoiceNumber;
        internal String mCode;
        internal Int64 mOperationID;
        internal String mOperationCode;
        internal String mOperationCodeWithoutDashes;
        internal String mMasterBL;
        internal String mMainRouteNotes;
        internal String mHouseNumber;
        internal Int32 mTransportType;
        internal Int32 mOperationStageID;
        internal String mOperationNotes;
        internal DateTime mOperationCloseDate;
        internal Boolean mIsOperationClosed;
        internal Int32 mBranchID;
        internal String mBranchName;
        internal Int32 mDirectionType;
        internal Int32 mBLType;
        internal String mPOLCode;
        internal String mPOLName;
        internal String mPODCountryName;
        internal String mPODCode;
        internal String mPODName;
        internal String mPODCountryCode;
        internal Int64 mMasterOperationID;
        internal String mMasterOperationCode;
        internal Int64 mOperationPartnerID;
        internal Int32 mPartnerTypeID;
        internal String mPartnerTypeCode;
        internal String mGeneralPartnerTypeCode;
        internal Int32 mPartnerID;
        internal String mPartnerName;
        internal String mPartnerLocalName;
        internal Boolean mIsInactive;
        internal String mVATNumber;
        internal String mInvoiceStatus;
        internal Int64 mAddressID;
        internal Int32 mCityID;
        internal String mCityName;
        internal Int32 mCountryID;
        internal String mCountryName;
        internal String mStreetLine1;
        internal String mStreetLine2;
        internal Int32 mAddressTypeID;
        internal String mAddressTypeName;
        internal String mPrintedAddress;
        internal String mCustomerReference;
        internal String mSupplierReference;
        internal Int32 mPaymentTermID;
        internal String mPaymentTermCode;
        internal String mPaymentTermName;
        internal Int32 mCurrencyID;
        internal String mCurrencyCode;
        internal Decimal mMasterDataExchangeRate;
        internal Decimal mExchangeRate;
        internal Decimal mAmountWithoutVAT;
        internal Int32 mTaxTypeID;
        internal String mTaxTypeName;
        internal Decimal mTaxPercentage;
        internal Decimal mTaxAmount;
        internal Int32 mDiscountTypeID;
        internal String mDiscountTypeName;
        internal Decimal mDiscountPercentage;
        internal Decimal mDiscountAmount;
        internal Decimal mFixedDiscount;
        internal Decimal mItems5PercTaxAmount;
        internal Decimal mItems10PercTaxAmount;
        internal Decimal mItems14PercTaxAmount;
        internal Decimal mVATFromItems;
        internal Decimal mDiscountFromItems;
        internal Decimal mAmount;
        internal Decimal mPaidAmount;
        internal Decimal mRemainingAmount;
        internal DateTime mInvoiceDate;
        internal DateTime mDueDate;
        internal Boolean mIsApproved;
        internal Boolean mIsDeleted;
        internal Int32 mApprovingUserID;
        internal String mApprovingUserName;
        internal Int32 mVesselID;
        internal String mVesselCode;
        internal String mVesselName;
        internal Int32 mLineID;
        internal String mLineName;
        internal String mVoyageOrTruckNumber;
        internal Int32 mNumberOfAccNotes;
        internal Int32 mNumberOfRoutings;
        internal Int32 mCreatorUserID;
        internal String mCreatorName;
        internal Int32 mSalesmanID;
        internal String mSalesmanName;
        internal DateTime mCreationDate;
        internal Int32 mModificatorUserID;
        internal String mModificatorName;
        internal DateTime mModificationDate;
        internal String mLeftSignature;
        internal String mMiddleSignature;
        internal String mRightSignature;
        internal Int32 mTaxAccount_ID;
        internal Int32 mTaxSubAccount_ID;
        internal Int32 mDiscAccount_ID;
        internal Int32 mDiscSubAccount_ID;
        internal String mGRT;
        internal String mDWT;
        internal String mNRT;
        internal String mLOA;
        internal Int64 mRoutingID;
        internal String mCertificateNumber;
        internal Int64 mOperationContainersAndPackagesID;
        internal String mTankOrFlexiNumber;
        internal Boolean mIsNeglectLimit;
        internal Int64 mRelatedToInvoiceID;
        internal Int64 mRelatedToInvoiceNumber;
        internal String mRelatedToInvoiceTypeName;
        internal DateTime mOperationOpenDate;
        internal Int64 mChildInvoiceID;
        internal Int64 mChildInvoiceNumber;
        internal String mChildInvoiceTypeName;
        internal Boolean mIsDraftApproved;
        internal Int32 mDraftApprovingUserID;
        internal DateTime mPaymentDate;
        internal Int32 mTransactionTypeID;
        internal DateTime mCutOffDate;
        internal String mNotes;
        internal String mEditableNotes;
        internal Boolean mIs3PL;
        internal Boolean mIsFleet;
        internal Boolean mIsPrintOriginal;
        internal Int64 mCancelledInvoiceID;
        internal Boolean mIsDelivered;
        internal Int32 mManualPaymentStatusID;
        internal String mManualPaymentStatusName;
        internal String mECode;
        #endregion

        #region "Methods"
        public Int64 ID
        {
            get { return mID; }
            set { mID = value; }
        }
        public Int64 InvoiceNumber
        {
            get { return mInvoiceNumber; }
            set { mInvoiceNumber = value; }
        }
        public Int32 InvoiceTypeID
        {
            get { return mInvoiceTypeID; }
            set { mInvoiceTypeID = value; }
        }
        public String InvoiceTypeCode
        {
            get { return mInvoiceTypeCode; }
            set { mInvoiceTypeCode = value; }
        }
        public String InvoiceTypeName
        {
            get { return mInvoiceTypeName; }
            set { mInvoiceTypeName = value; }
        }
        public String ConcatenatedInvoiceNumber
        {
            get { return mConcatenatedInvoiceNumber; }
            set { mConcatenatedInvoiceNumber = value; }
        }
        public String Code
        {
            get { return mCode; }
            set { mCode = value; }
        }
        public Int64 OperationID
        {
            get { return mOperationID; }
            set { mOperationID = value; }
        }
        public String OperationCode
        {
            get { return mOperationCode; }
            set { mOperationCode = value; }
        }
        public String OperationCodeWithoutDashes
        {
            get { return mOperationCodeWithoutDashes; }
            set { mOperationCodeWithoutDashes = value; }
        }
        public String MasterBL
        {
            get { return mMasterBL; }
            set { mMasterBL = value; }
        }
        public String MainRouteNotes
        {
            get { return mMainRouteNotes; }
            set { mMainRouteNotes = value; }
        }
        public String HouseNumber
        {
            get { return mHouseNumber; }
            set { mHouseNumber = value; }
        }
        public Int32 TransportType
        {
            get { return mTransportType; }
            set { mTransportType = value; }
        }
        public Int32 OperationStageID
        {
            get { return mOperationStageID; }
            set { mOperationStageID = value; }
        }
        public String OperationNotes
        {
            get { return mOperationNotes; }
            set { mOperationNotes = value; }
        }
        public DateTime OperationCloseDate
        {
            get { return mOperationCloseDate; }
            set { mOperationCloseDate = value; }
        }
        public Boolean IsOperationClosed
        {
            get { return mIsOperationClosed; }
            set { mIsOperationClosed = value; }
        }
        public Int32 BranchID
        {
            get { return mBranchID; }
            set { mBranchID = value; }
        }
        public String BranchName
        {
            get { return mBranchName; }
            set { mBranchName = value; }
        }
        public Int32 DirectionType
        {
            get { return mDirectionType; }
            set { mDirectionType = value; }
        }
        public Int32 BLType
        {
            get { return mBLType; }
            set { mBLType = value; }
        }
        public String POLCode
        {
            get { return mPOLCode; }
            set { mPOLCode = value; }
        }
        public String POLName
        {
            get { return mPOLName; }
            set { mPOLName = value; }
        }
        public String PODCountryName
        {
            get { return mPODCountryName; }
            set { mPODCountryName = value; }
        }
        public String PODCode
        {
            get { return mPODCode; }
            set { mPODCode = value; }
        }
        public String PODName
        {
            get { return mPODName; }
            set { mPODName = value; }
        }
        public String PODCountryCode
        {
            get { return mPODCountryCode; }
            set { mPODCountryCode = value; }
        }
        public Int64 MasterOperationID
        {
            get { return mMasterOperationID; }
            set { mMasterOperationID = value; }
        }
        public String MasterOperationCode
        {
            get { return mMasterOperationCode; }
            set { mMasterOperationCode = value; }
        }
        public Int64 OperationPartnerID
        {
            get { return mOperationPartnerID; }
            set { mOperationPartnerID = value; }
        }
        public Int32 PartnerTypeID
        {
            get { return mPartnerTypeID; }
            set { mPartnerTypeID = value; }
        }
        public String PartnerTypeCode
        {
            get { return mPartnerTypeCode; }
            set { mPartnerTypeCode = value; }
        }
        public String GeneralPartnerTypeCode
        {
            get { return mGeneralPartnerTypeCode; }
            set { mGeneralPartnerTypeCode = value; }
        }
        public Int32 PartnerID
        {
            get { return mPartnerID; }
            set { mPartnerID = value; }
        }
        public String PartnerName
        {
            get { return mPartnerName; }
            set { mPartnerName = value; }
        }
        public String PartnerLocalName
        {
            get { return mPartnerLocalName; }
            set { mPartnerLocalName = value; }
        }
        public Boolean IsInactive
        {
            get { return mIsInactive; }
            set { mIsInactive = value; }
        }
        public String VATNumber
        {
            get { return mVATNumber; }
            set { mVATNumber = value; }
        }
        public String InvoiceStatus
        {
            get { return mInvoiceStatus; }
            set { mInvoiceStatus = value; }
        }
        public Int64 AddressID
        {
            get { return mAddressID; }
            set { mAddressID = value; }
        }
        public Int32 CityID
        {
            get { return mCityID; }
            set { mCityID = value; }
        }
        public String CityName
        {
            get { return mCityName; }
            set { mCityName = value; }
        }
        public Int32 CountryID
        {
            get { return mCountryID; }
            set { mCountryID = value; }
        }
        public String CountryName
        {
            get { return mCountryName; }
            set { mCountryName = value; }
        }
        public String StreetLine1
        {
            get { return mStreetLine1; }
            set { mStreetLine1 = value; }
        }
        public String StreetLine2
        {
            get { return mStreetLine2; }
            set { mStreetLine2 = value; }
        }
        public Int32 AddressTypeID
        {
            get { return mAddressTypeID; }
            set { mAddressTypeID = value; }
        }
        public String AddressTypeName
        {
            get { return mAddressTypeName; }
            set { mAddressTypeName = value; }
        }
        public String PrintedAddress
        {
            get { return mPrintedAddress; }
            set { mPrintedAddress = value; }
        }
        public String CustomerReference
        {
            get { return mCustomerReference; }
            set { mCustomerReference = value; }
        }
        public String SupplierReference
        {
            get { return mSupplierReference; }
            set { mSupplierReference = value; }
        }
        public Int32 PaymentTermID
        {
            get { return mPaymentTermID; }
            set { mPaymentTermID = value; }
        }
        public String PaymentTermCode
        {
            get { return mPaymentTermCode; }
            set { mPaymentTermCode = value; }
        }
        public String PaymentTermName
        {
            get { return mPaymentTermName; }
            set { mPaymentTermName = value; }
        }
        public Int32 CurrencyID
        {
            get { return mCurrencyID; }
            set { mCurrencyID = value; }
        }
        public String CurrencyCode
        {
            get { return mCurrencyCode; }
            set { mCurrencyCode = value; }
        }
        public Decimal MasterDataExchangeRate
        {
            get { return mMasterDataExchangeRate; }
            set { mMasterDataExchangeRate = value; }
        }
        public Decimal ExchangeRate
        {
            get { return mExchangeRate; }
            set { mExchangeRate = value; }
        }
        public Decimal AmountWithoutVAT
        {
            get { return mAmountWithoutVAT; }
            set { mAmountWithoutVAT = value; }
        }
        public Int32 TaxTypeID
        {
            get { return mTaxTypeID; }
            set { mTaxTypeID = value; }
        }
        public String TaxTypeName
        {
            get { return mTaxTypeName; }
            set { mTaxTypeName = value; }
        }
        public Decimal TaxPercentage
        {
            get { return mTaxPercentage; }
            set { mTaxPercentage = value; }
        }
        public Decimal TaxAmount
        {
            get { return mTaxAmount; }
            set { mTaxAmount = value; }
        }
        public Int32 DiscountTypeID
        {
            get { return mDiscountTypeID; }
            set { mDiscountTypeID = value; }
        }
        public String DiscountTypeName
        {
            get { return mDiscountTypeName; }
            set { mDiscountTypeName = value; }
        }
        public Decimal DiscountPercentage
        {
            get { return mDiscountPercentage; }
            set { mDiscountPercentage = value; }
        }
        public Decimal DiscountAmount
        {
            get { return mDiscountAmount; }
            set { mDiscountAmount = value; }
        }
        public Decimal FixedDiscount
        {
            get { return mFixedDiscount; }
            set { mFixedDiscount = value; }
        }
        public Decimal Items5PercTaxAmount
        {
            get { return mItems5PercTaxAmount; }
            set { mItems5PercTaxAmount = value; }
        }
        public Decimal Items10PercTaxAmount
        {
            get { return mItems10PercTaxAmount; }
            set { mItems10PercTaxAmount = value; }
        }
        public Decimal Items14PercTaxAmount
        {
            get { return mItems14PercTaxAmount; }
            set { mItems14PercTaxAmount = value; }
        }
        public Decimal VATFromItems
        {
            get { return mVATFromItems; }
            set { mVATFromItems = value; }
        }
        public Decimal DiscountFromItems
        {
            get { return mDiscountFromItems; }
            set { mDiscountFromItems = value; }
        }
        public Decimal Amount
        {
            get { return mAmount; }
            set { mAmount = value; }
        }
        public Decimal PaidAmount
        {
            get { return mPaidAmount; }
            set { mPaidAmount = value; }
        }
        public Decimal RemainingAmount
        {
            get { return mRemainingAmount; }
            set { mRemainingAmount = value; }
        }
        public DateTime InvoiceDate
        {
            get { return mInvoiceDate; }
            set { mInvoiceDate = value; }
        }
        public DateTime DueDate
        {
            get { return mDueDate; }
            set { mDueDate = value; }
        }
        public Boolean IsApproved
        {
            get { return mIsApproved; }
            set { mIsApproved = value; }
        }
        public Boolean IsDeleted
        {
            get { return mIsDeleted; }
            set { mIsDeleted = value; }
        }
        public Int32 ApprovingUserID
        {
            get { return mApprovingUserID; }
            set { mApprovingUserID = value; }
        }
        public String ApprovingUserName
        {
            get { return mApprovingUserName; }
            set { mApprovingUserName = value; }
        }
        public Int32 VesselID
        {
            get { return mVesselID; }
            set { mVesselID = value; }
        }
        public String VesselCode
        {
            get { return mVesselCode; }
            set { mVesselCode = value; }
        }
        public String VesselName
        {
            get { return mVesselName; }
            set { mVesselName = value; }
        }
        public Int32 LineID
        {
            get { return mLineID; }
            set { mLineID = value; }
        }
        public String LineName
        {
            get { return mLineName; }
            set { mLineName = value; }
        }
        public String VoyageOrTruckNumber
        {
            get { return mVoyageOrTruckNumber; }
            set { mVoyageOrTruckNumber = value; }
        }
        public Int32 NumberOfAccNotes
        {
            get { return mNumberOfAccNotes; }
            set { mNumberOfAccNotes = value; }
        }
        public Int32 NumberOfRoutings
        {
            get { return mNumberOfRoutings; }
            set { mNumberOfRoutings = value; }
        }
        public Int32 CreatorUserID
        {
            get { return mCreatorUserID; }
            set { mCreatorUserID = value; }
        }
        public String CreatorName
        {
            get { return mCreatorName; }
            set { mCreatorName = value; }
        }
        public Int32 SalesmanID
        {
            get { return mSalesmanID; }
            set { mSalesmanID = value; }
        }
        public String SalesmanName
        {
            get { return mSalesmanName; }
            set { mSalesmanName = value; }
        }
        public DateTime CreationDate
        {
            get { return mCreationDate; }
            set { mCreationDate = value; }
        }
        public Int32 ModificatorUserID
        {
            get { return mModificatorUserID; }
            set { mModificatorUserID = value; }
        }
        public String ModificatorName
        {
            get { return mModificatorName; }
            set { mModificatorName = value; }
        }
        public DateTime ModificationDate
        {
            get { return mModificationDate; }
            set { mModificationDate = value; }
        }
        public String LeftSignature
        {
            get { return mLeftSignature; }
            set { mLeftSignature = value; }
        }
        public String MiddleSignature
        {
            get { return mMiddleSignature; }
            set { mMiddleSignature = value; }
        }
        public String RightSignature
        {
            get { return mRightSignature; }
            set { mRightSignature = value; }
        }
        public Int32 TaxAccount_ID
        {
            get { return mTaxAccount_ID; }
            set { mTaxAccount_ID = value; }
        }
        public Int32 TaxSubAccount_ID
        {
            get { return mTaxSubAccount_ID; }
            set { mTaxSubAccount_ID = value; }
        }
        public Int32 DiscAccount_ID
        {
            get { return mDiscAccount_ID; }
            set { mDiscAccount_ID = value; }
        }
        public Int32 DiscSubAccount_ID
        {
            get { return mDiscSubAccount_ID; }
            set { mDiscSubAccount_ID = value; }
        }
        public String GRT
        {
            get { return mGRT; }
            set { mGRT = value; }
        }
        public String DWT
        {
            get { return mDWT; }
            set { mDWT = value; }
        }
        public String NRT
        {
            get { return mNRT; }
            set { mNRT = value; }
        }
        public String LOA
        {
            get { return mLOA; }
            set { mLOA = value; }
        }
        public Int64 RoutingID
        {
            get { return mRoutingID; }
            set { mRoutingID = value; }
        }
        public String CertificateNumber
        {
            get { return mCertificateNumber; }
            set { mCertificateNumber = value; }
        }
        public Int64 OperationContainersAndPackagesID
        {
            get { return mOperationContainersAndPackagesID; }
            set { mOperationContainersAndPackagesID = value; }
        }
        public String TankOrFlexiNumber
        {
            get { return mTankOrFlexiNumber; }
            set { mTankOrFlexiNumber = value; }
        }
        public Boolean IsNeglectLimit
        {
            get { return mIsNeglectLimit; }
            set { mIsNeglectLimit = value; }
        }
        public Int64 RelatedToInvoiceID
        {
            get { return mRelatedToInvoiceID; }
            set { mRelatedToInvoiceID = value; }
        }
        public Int64 RelatedToInvoiceNumber
        {
            get { return mRelatedToInvoiceNumber; }
            set { mRelatedToInvoiceNumber = value; }
        }
        public String RelatedToInvoiceTypeName
        {
            get { return mRelatedToInvoiceTypeName; }
            set { mRelatedToInvoiceTypeName = value; }
        }
        public DateTime OperationOpenDate
        {
            get { return mOperationOpenDate; }
            set { mOperationOpenDate = value; }
        }
        public Int64 ChildInvoiceID
        {
            get { return mChildInvoiceID; }
            set { mChildInvoiceID = value; }
        }
        public Int64 ChildInvoiceNumber
        {
            get { return mChildInvoiceNumber; }
            set { mChildInvoiceNumber = value; }
        }
        public String ChildInvoiceTypeName
        {
            get { return mChildInvoiceTypeName; }
            set { mChildInvoiceTypeName = value; }
        }
        public Boolean IsDraftApproved
        {
            get { return mIsDraftApproved; }
            set { mIsDraftApproved = value; }
        }
        public Int32 DraftApprovingUserID
        {
            get { return mDraftApprovingUserID; }
            set { mDraftApprovingUserID = value; }
        }
        public DateTime PaymentDate
        {
            get { return mPaymentDate; }
            set { mPaymentDate = value; }
        }
        public Int32 TransactionTypeID
        {
            get { return mTransactionTypeID; }
            set { mTransactionTypeID = value; }
        }
        public DateTime CutOffDate
        {
            get { return mCutOffDate; }
            set { mCutOffDate = value; }
        }
        public String Notes
        {
            get { return mNotes; }
            set { mNotes = value; }
        }
        public String EditableNotes
        {
            get { return mEditableNotes; }
            set { mEditableNotes = value; }
        }
        public Boolean Is3PL
        {
            get { return mIs3PL; }
            set { mIs3PL = value; }
        }
        public Boolean IsFleet
        {
            get { return mIsFleet; }
            set { mIsFleet = value; }
        }
        public Boolean IsPrintOriginal
        {
            get { return mIsPrintOriginal; }
            set { mIsPrintOriginal = value; }
        }
        public Int64 CancelledInvoiceID
        {
            get { return mCancelledInvoiceID; }
            set { mCancelledInvoiceID = value; }
        }
        public Boolean IsDelivered
        {
            get { return mIsDelivered; }
            set { mIsDelivered = value; }
        }
        public Int32 ManualPaymentStatusID
        {
            get { return mManualPaymentStatusID; }
            set { mManualPaymentStatusID = value; }
        }
        public String ManualPaymentStatusName
        {
            get { return mManualPaymentStatusName; }
            set { mManualPaymentStatusName = value; }
        }
        public String ECode
        {
            get { return mECode; }
            set { mECode = value; }
        }
        #endregion
    }

    public partial class CvwInvoices
    {
        #region "variables"
        /*If "App.Config" isnot exist add it to your Application
		Add this code after <Configuration> tag
		-------------------------------------------------------
		<appsettings>
		<add key="ConnectionString" value="............"/>
		</appsettings>
		-------------------------------------------------------
		where ".........." is connection string to database server*/
        private SqlTransaction tr;
        public List<CVarvwInvoices> lstCVarvwInvoices = new List<CVarvwInvoices>();
        #endregion

        #region "Select Methods"
        public Exception GetList(string WhereClause)
        {
            return DataFill(WhereClause, true);
        }
        public Exception GetListPaging(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotalRecords)
        {
            return DataFill(PageSize, PageNumber, WhereClause, OrderBy, out TotalRecords);
        }
        private Exception DataFill(string Param, Boolean IsList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarvwInvoices.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                if (IsList == true)
                {
                    Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar));
                    Com.CommandText = "[dbo].GetListvwInvoices";
                    Com.Parameters[0].Value = Param;
                }
                Com.Transaction = tr;
                Com.Connection = Con;
                Com.CommandTimeout = 3000;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarvwInvoices ObjCVarvwInvoices = new CVarvwInvoices();
                        ObjCVarvwInvoices.mID = Convert.ToInt64(dr["ID"].ToString());
                        ObjCVarvwInvoices.mInvoiceNumber = Convert.ToInt64(dr["InvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mInvoiceTypeID = Convert.ToInt32(dr["InvoiceTypeID"].ToString());
                        ObjCVarvwInvoices.mInvoiceTypeCode = Convert.ToString(dr["InvoiceTypeCode"].ToString());
                        ObjCVarvwInvoices.mInvoiceTypeName = Convert.ToString(dr["InvoiceTypeName"].ToString());
                        ObjCVarvwInvoices.mConcatenatedInvoiceNumber = Convert.ToString(dr["ConcatenatedInvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mCode = Convert.ToString(dr["Code"].ToString());
                        ObjCVarvwInvoices.mOperationID = Convert.ToInt64(dr["OperationID"].ToString());
                        ObjCVarvwInvoices.mOperationCode = Convert.ToString(dr["OperationCode"].ToString());
                        ObjCVarvwInvoices.mOperationCodeWithoutDashes = Convert.ToString(dr["OperationCodeWithoutDashes"].ToString());
                        ObjCVarvwInvoices.mMasterBL = Convert.ToString(dr["MasterBL"].ToString());
                        ObjCVarvwInvoices.mMainRouteNotes = Convert.ToString(dr["MainRouteNotes"].ToString());
                        ObjCVarvwInvoices.mHouseNumber = Convert.ToString(dr["HouseNumber"].ToString());
                        ObjCVarvwInvoices.mTransportType = Convert.ToInt32(dr["TransportType"].ToString());
                        ObjCVarvwInvoices.mOperationStageID = Convert.ToInt32(dr["OperationStageID"].ToString());
                        ObjCVarvwInvoices.mOperationNotes = Convert.ToString(dr["OperationNotes"].ToString());
                        ObjCVarvwInvoices.mOperationCloseDate = Convert.ToDateTime(dr["OperationCloseDate"].ToString());
                        ObjCVarvwInvoices.mIsOperationClosed = Convert.ToBoolean(dr["IsOperationClosed"].ToString());
                        ObjCVarvwInvoices.mBranchID = Convert.ToInt32(dr["BranchID"].ToString());
                        ObjCVarvwInvoices.mBranchName = Convert.ToString(dr["BranchName"].ToString());
                        ObjCVarvwInvoices.mDirectionType = Convert.ToInt32(dr["DirectionType"].ToString());
                        ObjCVarvwInvoices.mBLType = Convert.ToInt32(dr["BLType"].ToString());
                        ObjCVarvwInvoices.mPOLCode = Convert.ToString(dr["POLCode"].ToString());
                        ObjCVarvwInvoices.mPOLName = Convert.ToString(dr["POLName"].ToString());
                        ObjCVarvwInvoices.mPODCountryName = Convert.ToString(dr["PODCountryName"].ToString());
                        ObjCVarvwInvoices.mPODCode = Convert.ToString(dr["PODCode"].ToString());
                        ObjCVarvwInvoices.mPODName = Convert.ToString(dr["PODName"].ToString());
                        ObjCVarvwInvoices.mPODCountryCode = Convert.ToString(dr["PODCountryCode"].ToString());
                        ObjCVarvwInvoices.mMasterOperationID = Convert.ToInt64(dr["MasterOperationID"].ToString());
                        ObjCVarvwInvoices.mMasterOperationCode = Convert.ToString(dr["MasterOperationCode"].ToString());
                        ObjCVarvwInvoices.mOperationPartnerID = Convert.ToInt64(dr["OperationPartnerID"].ToString());
                        ObjCVarvwInvoices.mPartnerTypeID = Convert.ToInt32(dr["PartnerTypeID"].ToString());
                        ObjCVarvwInvoices.mPartnerTypeCode = Convert.ToString(dr["PartnerTypeCode"].ToString());
                        ObjCVarvwInvoices.mGeneralPartnerTypeCode = Convert.ToString(dr["GeneralPartnerTypeCode"].ToString());
                        ObjCVarvwInvoices.mPartnerID = Convert.ToInt32(dr["PartnerID"].ToString());
                        ObjCVarvwInvoices.mPartnerName = Convert.ToString(dr["PartnerName"].ToString());
                        ObjCVarvwInvoices.mPartnerLocalName = Convert.ToString(dr["PartnerLocalName"].ToString());
                        ObjCVarvwInvoices.mIsInactive = Convert.ToBoolean(dr["IsInactive"].ToString());
                        ObjCVarvwInvoices.mVATNumber = Convert.ToString(dr["VATNumber"].ToString());
                        ObjCVarvwInvoices.mInvoiceStatus = Convert.ToString(dr["InvoiceStatus"].ToString());
                        ObjCVarvwInvoices.mAddressID = Convert.ToInt64(dr["AddressID"].ToString());
                        ObjCVarvwInvoices.mCityID = Convert.ToInt32(dr["CityID"].ToString());
                        ObjCVarvwInvoices.mCityName = Convert.ToString(dr["CityName"].ToString());
                        ObjCVarvwInvoices.mCountryID = Convert.ToInt32(dr["CountryID"].ToString());
                        ObjCVarvwInvoices.mCountryName = Convert.ToString(dr["CountryName"].ToString());
                        ObjCVarvwInvoices.mStreetLine1 = Convert.ToString(dr["StreetLine1"].ToString());
                        ObjCVarvwInvoices.mStreetLine2 = Convert.ToString(dr["StreetLine2"].ToString());
                        ObjCVarvwInvoices.mAddressTypeID = Convert.ToInt32(dr["AddressTypeID"].ToString());
                        ObjCVarvwInvoices.mAddressTypeName = Convert.ToString(dr["AddressTypeName"].ToString());
                        ObjCVarvwInvoices.mPrintedAddress = Convert.ToString(dr["PrintedAddress"].ToString());
                        ObjCVarvwInvoices.mCustomerReference = Convert.ToString(dr["CustomerReference"].ToString());
                        ObjCVarvwInvoices.mSupplierReference = Convert.ToString(dr["SupplierReference"].ToString());
                        ObjCVarvwInvoices.mPaymentTermID = Convert.ToInt32(dr["PaymentTermID"].ToString());
                        ObjCVarvwInvoices.mPaymentTermCode = Convert.ToString(dr["PaymentTermCode"].ToString());
                        ObjCVarvwInvoices.mPaymentTermName = Convert.ToString(dr["PaymentTermName"].ToString());
                        ObjCVarvwInvoices.mCurrencyID = Convert.ToInt32(dr["CurrencyID"].ToString());
                        ObjCVarvwInvoices.mCurrencyCode = Convert.ToString(dr["CurrencyCode"].ToString());
                        ObjCVarvwInvoices.mMasterDataExchangeRate = Convert.ToDecimal(dr["MasterDataExchangeRate"].ToString());
                        ObjCVarvwInvoices.mExchangeRate = Convert.ToDecimal(dr["ExchangeRate"].ToString());
                        ObjCVarvwInvoices.mAmountWithoutVAT = Convert.ToDecimal(dr["AmountWithoutVAT"].ToString());
                        ObjCVarvwInvoices.mTaxTypeID = Convert.ToInt32(dr["TaxTypeID"].ToString());
                        ObjCVarvwInvoices.mTaxTypeName = Convert.ToString(dr["TaxTypeName"].ToString());
                        ObjCVarvwInvoices.mTaxPercentage = Convert.ToDecimal(dr["TaxPercentage"].ToString());
                        ObjCVarvwInvoices.mTaxAmount = Convert.ToDecimal(dr["TaxAmount"].ToString());
                        ObjCVarvwInvoices.mDiscountTypeID = Convert.ToInt32(dr["DiscountTypeID"].ToString());
                        ObjCVarvwInvoices.mDiscountTypeName = Convert.ToString(dr["DiscountTypeName"].ToString());
                        ObjCVarvwInvoices.mDiscountPercentage = Convert.ToDecimal(dr["DiscountPercentage"].ToString());
                        ObjCVarvwInvoices.mDiscountAmount = Convert.ToDecimal(dr["DiscountAmount"].ToString());
                        ObjCVarvwInvoices.mFixedDiscount = Convert.ToDecimal(dr["FixedDiscount"].ToString());
                        ObjCVarvwInvoices.mItems5PercTaxAmount = Convert.ToDecimal(dr["Items5PercTaxAmount"].ToString());
                        ObjCVarvwInvoices.mItems10PercTaxAmount = Convert.ToDecimal(dr["Items10PercTaxAmount"].ToString());
                        ObjCVarvwInvoices.mItems14PercTaxAmount = Convert.ToDecimal(dr["Items14PercTaxAmount"].ToString());
                        ObjCVarvwInvoices.mVATFromItems = Convert.ToDecimal(dr["VATFromItems"].ToString());
                        ObjCVarvwInvoices.mDiscountFromItems = Convert.ToDecimal(dr["DiscountFromItems"].ToString());
                        ObjCVarvwInvoices.mAmount = Convert.ToDecimal(dr["Amount"].ToString());
                        ObjCVarvwInvoices.mPaidAmount = Convert.ToDecimal(dr["PaidAmount"].ToString());
                        ObjCVarvwInvoices.mRemainingAmount = Convert.ToDecimal(dr["RemainingAmount"].ToString());
                        ObjCVarvwInvoices.mInvoiceDate = Convert.ToDateTime(dr["InvoiceDate"].ToString());
                        ObjCVarvwInvoices.mDueDate = Convert.ToDateTime(dr["DueDate"].ToString());
                        ObjCVarvwInvoices.mIsApproved = Convert.ToBoolean(dr["IsApproved"].ToString());
                        ObjCVarvwInvoices.mIsDeleted = Convert.ToBoolean(dr["IsDeleted"].ToString());
                        ObjCVarvwInvoices.mApprovingUserID = Convert.ToInt32(dr["ApprovingUserID"].ToString());
                        ObjCVarvwInvoices.mApprovingUserName = Convert.ToString(dr["ApprovingUserName"].ToString());
                        ObjCVarvwInvoices.mVesselID = Convert.ToInt32(dr["VesselID"].ToString());
                        ObjCVarvwInvoices.mVesselCode = Convert.ToString(dr["VesselCode"].ToString());
                        ObjCVarvwInvoices.mVesselName = Convert.ToString(dr["VesselName"].ToString());
                        ObjCVarvwInvoices.mLineID = Convert.ToInt32(dr["LineID"].ToString());
                        ObjCVarvwInvoices.mLineName = Convert.ToString(dr["LineName"].ToString());
                        ObjCVarvwInvoices.mVoyageOrTruckNumber = Convert.ToString(dr["VoyageOrTruckNumber"].ToString());
                        ObjCVarvwInvoices.mNumberOfAccNotes = Convert.ToInt32(dr["NumberOfAccNotes"].ToString());
                        ObjCVarvwInvoices.mNumberOfRoutings = Convert.ToInt32(dr["NumberOfRoutings"].ToString());
                        ObjCVarvwInvoices.mCreatorUserID = Convert.ToInt32(dr["CreatorUserID"].ToString());
                        ObjCVarvwInvoices.mCreatorName = Convert.ToString(dr["CreatorName"].ToString());
                        ObjCVarvwInvoices.mSalesmanID = Convert.ToInt32(dr["SalesmanID"].ToString());
                        ObjCVarvwInvoices.mSalesmanName = Convert.ToString(dr["SalesmanName"].ToString());
                        ObjCVarvwInvoices.mCreationDate = Convert.ToDateTime(dr["CreationDate"].ToString());
                        ObjCVarvwInvoices.mModificatorUserID = Convert.ToInt32(dr["ModificatorUserID"].ToString());
                        ObjCVarvwInvoices.mModificatorName = Convert.ToString(dr["ModificatorName"].ToString());
                        ObjCVarvwInvoices.mModificationDate = Convert.ToDateTime(dr["ModificationDate"].ToString());
                        ObjCVarvwInvoices.mLeftSignature = Convert.ToString(dr["LeftSignature"].ToString());
                        ObjCVarvwInvoices.mMiddleSignature = Convert.ToString(dr["MiddleSignature"].ToString());
                        ObjCVarvwInvoices.mRightSignature = Convert.ToString(dr["RightSignature"].ToString());
                        ObjCVarvwInvoices.mTaxAccount_ID = Convert.ToInt32(dr["TaxAccount_ID"].ToString());
                        ObjCVarvwInvoices.mTaxSubAccount_ID = Convert.ToInt32(dr["TaxSubAccount_ID"].ToString());
                        ObjCVarvwInvoices.mDiscAccount_ID = Convert.ToInt32(dr["DiscAccount_ID"].ToString());
                        ObjCVarvwInvoices.mDiscSubAccount_ID = Convert.ToInt32(dr["DiscSubAccount_ID"].ToString());
                        ObjCVarvwInvoices.mGRT = Convert.ToString(dr["GRT"].ToString());
                        ObjCVarvwInvoices.mDWT = Convert.ToString(dr["DWT"].ToString());
                        ObjCVarvwInvoices.mNRT = Convert.ToString(dr["NRT"].ToString());
                        ObjCVarvwInvoices.mLOA = Convert.ToString(dr["LOA"].ToString());
                        ObjCVarvwInvoices.mRoutingID = Convert.ToInt64(dr["RoutingID"].ToString());
                        ObjCVarvwInvoices.mCertificateNumber = Convert.ToString(dr["CertificateNumber"].ToString());
                        ObjCVarvwInvoices.mOperationContainersAndPackagesID = Convert.ToInt64(dr["OperationContainersAndPackagesID"].ToString());
                        ObjCVarvwInvoices.mTankOrFlexiNumber = Convert.ToString(dr["TankOrFlexiNumber"].ToString());
                        ObjCVarvwInvoices.mIsNeglectLimit = Convert.ToBoolean(dr["IsNeglectLimit"].ToString());
                        ObjCVarvwInvoices.mRelatedToInvoiceID = Convert.ToInt64(dr["RelatedToInvoiceID"].ToString());
                        ObjCVarvwInvoices.mRelatedToInvoiceNumber = Convert.ToInt64(dr["RelatedToInvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mRelatedToInvoiceTypeName = Convert.ToString(dr["RelatedToInvoiceTypeName"].ToString());
                        ObjCVarvwInvoices.mOperationOpenDate = Convert.ToDateTime(dr["OperationOpenDate"].ToString());
                        ObjCVarvwInvoices.mChildInvoiceID = Convert.ToInt64(dr["ChildInvoiceID"].ToString());
                        ObjCVarvwInvoices.mChildInvoiceNumber = Convert.ToInt64(dr["ChildInvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mChildInvoiceTypeName = Convert.ToString(dr["ChildInvoiceTypeName"].ToString());
                        ObjCVarvwInvoices.mIsDraftApproved = Convert.ToBoolean(dr["IsDraftApproved"].ToString());
                        ObjCVarvwInvoices.mDraftApprovingUserID = Convert.ToInt32(dr["DraftApprovingUserID"].ToString());
                        ObjCVarvwInvoices.mPaymentDate = Convert.ToDateTime(dr["PaymentDate"].ToString());
                        ObjCVarvwInvoices.mTransactionTypeID = Convert.ToInt32(dr["TransactionTypeID"].ToString());
                        ObjCVarvwInvoices.mCutOffDate = Convert.ToDateTime(dr["CutOffDate"].ToString());
                        ObjCVarvwInvoices.mNotes = Convert.ToString(dr["Notes"].ToString());
                        ObjCVarvwInvoices.mEditableNotes = Convert.ToString(dr["EditableNotes"].ToString());
                        ObjCVarvwInvoices.mIs3PL = Convert.ToBoolean(dr["Is3PL"].ToString());
                        ObjCVarvwInvoices.mIsFleet = Convert.ToBoolean(dr["IsFleet"].ToString());
                        ObjCVarvwInvoices.mIsPrintOriginal = Convert.ToBoolean(dr["IsPrintOriginal"].ToString());
                        ObjCVarvwInvoices.mCancelledInvoiceID = Convert.ToInt64(dr["CancelledInvoiceID"].ToString());
                        ObjCVarvwInvoices.mIsDelivered = Convert.ToBoolean(dr["IsDelivered"].ToString());
                        ObjCVarvwInvoices.mManualPaymentStatusID = Convert.ToInt32(dr["ManualPaymentStatusID"].ToString());
                        ObjCVarvwInvoices.mManualPaymentStatusName = Convert.ToString(dr["ManualPaymentStatusName"].ToString());
                        ObjCVarvwInvoices.mECode = Convert.ToString(dr["ECode"].ToString());
                        lstCVarvwInvoices.Add(ObjCVarvwInvoices);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        private Exception DataFill(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotRecs)
        {
            Exception Exp = null;
            TotRecs = 0;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarvwInvoices.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                Com.Parameters.Add(new SqlParameter("@PageSize", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@PageNumber", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.VarChar));
                Com.Parameters.Add(new SqlParameter("@OrderBy", SqlDbType.VarChar));
                Com.CommandText = "[dbo].GetListPagingvwInvoices";
                Com.Parameters[0].Value = PageSize;
                Com.Parameters[1].Value = PageNumber;
                Com.Parameters[2].Value = WhereClause;
                Com.Parameters[3].Value = OrderBy;
                Com.Transaction = tr;
                Com.Connection = Con;
                Com.CommandTimeout = 3000;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarvwInvoices ObjCVarvwInvoices = new CVarvwInvoices();
                        ObjCVarvwInvoices.mID = Convert.ToInt64(dr["ID"].ToString());
                        ObjCVarvwInvoices.mInvoiceNumber = Convert.ToInt64(dr["InvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mInvoiceTypeID = Convert.ToInt32(dr["InvoiceTypeID"].ToString());
                        ObjCVarvwInvoices.mInvoiceTypeCode = Convert.ToString(dr["InvoiceTypeCode"].ToString());
                        ObjCVarvwInvoices.mInvoiceTypeName = Convert.ToString(dr["InvoiceTypeName"].ToString());
                        ObjCVarvwInvoices.mConcatenatedInvoiceNumber = Convert.ToString(dr["ConcatenatedInvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mCode = Convert.ToString(dr["Code"].ToString());
                        ObjCVarvwInvoices.mOperationID = Convert.ToInt64(dr["OperationID"].ToString());
                        ObjCVarvwInvoices.mOperationCode = Convert.ToString(dr["OperationCode"].ToString());
                        ObjCVarvwInvoices.mOperationCodeWithoutDashes = Convert.ToString(dr["OperationCodeWithoutDashes"].ToString());
                        ObjCVarvwInvoices.mMasterBL = Convert.ToString(dr["MasterBL"].ToString());
                        ObjCVarvwInvoices.mMainRouteNotes = Convert.ToString(dr["MainRouteNotes"].ToString());
                        ObjCVarvwInvoices.mHouseNumber = Convert.ToString(dr["HouseNumber"].ToString());
                        ObjCVarvwInvoices.mTransportType = Convert.ToInt32(dr["TransportType"].ToString());
                        ObjCVarvwInvoices.mOperationStageID = Convert.ToInt32(dr["OperationStageID"].ToString());
                        ObjCVarvwInvoices.mOperationNotes = Convert.ToString(dr["OperationNotes"].ToString());
                        ObjCVarvwInvoices.mOperationCloseDate = Convert.ToDateTime(dr["OperationCloseDate"].ToString());
                        ObjCVarvwInvoices.mIsOperationClosed = Convert.ToBoolean(dr["IsOperationClosed"].ToString());
                        ObjCVarvwInvoices.mBranchID = Convert.ToInt32(dr["BranchID"].ToString());
                        ObjCVarvwInvoices.mBranchName = Convert.ToString(dr["BranchName"].ToString());
                        ObjCVarvwInvoices.mDirectionType = Convert.ToInt32(dr["DirectionType"].ToString());
                        ObjCVarvwInvoices.mBLType = Convert.ToInt32(dr["BLType"].ToString());
                        ObjCVarvwInvoices.mPOLCode = Convert.ToString(dr["POLCode"].ToString());
                        ObjCVarvwInvoices.mPOLName = Convert.ToString(dr["POLName"].ToString());
                        ObjCVarvwInvoices.mPODCountryName = Convert.ToString(dr["PODCountryName"].ToString());
                        ObjCVarvwInvoices.mPODCode = Convert.ToString(dr["PODCode"].ToString());
                        ObjCVarvwInvoices.mPODName = Convert.ToString(dr["PODName"].ToString());
                        ObjCVarvwInvoices.mPODCountryCode = Convert.ToString(dr["PODCountryCode"].ToString());
                        ObjCVarvwInvoices.mMasterOperationID = Convert.ToInt64(dr["MasterOperationID"].ToString());
                        ObjCVarvwInvoices.mMasterOperationCode = Convert.ToString(dr["MasterOperationCode"].ToString());
                        ObjCVarvwInvoices.mOperationPartnerID = Convert.ToInt64(dr["OperationPartnerID"].ToString());
                        ObjCVarvwInvoices.mPartnerTypeID = Convert.ToInt32(dr["PartnerTypeID"].ToString());
                        ObjCVarvwInvoices.mPartnerTypeCode = Convert.ToString(dr["PartnerTypeCode"].ToString());
                        ObjCVarvwInvoices.mGeneralPartnerTypeCode = Convert.ToString(dr["GeneralPartnerTypeCode"].ToString());
                        ObjCVarvwInvoices.mPartnerID = Convert.ToInt32(dr["PartnerID"].ToString());
                        ObjCVarvwInvoices.mPartnerName = Convert.ToString(dr["PartnerName"].ToString());
                        ObjCVarvwInvoices.mPartnerLocalName = Convert.ToString(dr["PartnerLocalName"].ToString());
                        ObjCVarvwInvoices.mIsInactive = Convert.ToBoolean(dr["IsInactive"].ToString());
                        ObjCVarvwInvoices.mVATNumber = Convert.ToString(dr["VATNumber"].ToString());
                        ObjCVarvwInvoices.mInvoiceStatus = Convert.ToString(dr["InvoiceStatus"].ToString());
                        ObjCVarvwInvoices.mAddressID = Convert.ToInt64(dr["AddressID"].ToString());
                        ObjCVarvwInvoices.mCityID = Convert.ToInt32(dr["CityID"].ToString());
                        ObjCVarvwInvoices.mCityName = Convert.ToString(dr["CityName"].ToString());
                        ObjCVarvwInvoices.mCountryID = Convert.ToInt32(dr["CountryID"].ToString());
                        ObjCVarvwInvoices.mCountryName = Convert.ToString(dr["CountryName"].ToString());
                        ObjCVarvwInvoices.mStreetLine1 = Convert.ToString(dr["StreetLine1"].ToString());
                        ObjCVarvwInvoices.mStreetLine2 = Convert.ToString(dr["StreetLine2"].ToString());
                        ObjCVarvwInvoices.mAddressTypeID = Convert.ToInt32(dr["AddressTypeID"].ToString());
                        ObjCVarvwInvoices.mAddressTypeName = Convert.ToString(dr["AddressTypeName"].ToString());
                        ObjCVarvwInvoices.mPrintedAddress = Convert.ToString(dr["PrintedAddress"].ToString());
                        ObjCVarvwInvoices.mCustomerReference = Convert.ToString(dr["CustomerReference"].ToString());
                        ObjCVarvwInvoices.mSupplierReference = Convert.ToString(dr["SupplierReference"].ToString());
                        ObjCVarvwInvoices.mPaymentTermID = Convert.ToInt32(dr["PaymentTermID"].ToString());
                        ObjCVarvwInvoices.mPaymentTermCode = Convert.ToString(dr["PaymentTermCode"].ToString());
                        ObjCVarvwInvoices.mPaymentTermName = Convert.ToString(dr["PaymentTermName"].ToString());
                        ObjCVarvwInvoices.mCurrencyID = Convert.ToInt32(dr["CurrencyID"].ToString());
                        ObjCVarvwInvoices.mCurrencyCode = Convert.ToString(dr["CurrencyCode"].ToString());
                        ObjCVarvwInvoices.mMasterDataExchangeRate = Convert.ToDecimal(dr["MasterDataExchangeRate"].ToString());
                        ObjCVarvwInvoices.mExchangeRate = Convert.ToDecimal(dr["ExchangeRate"].ToString());
                        ObjCVarvwInvoices.mAmountWithoutVAT = Convert.ToDecimal(dr["AmountWithoutVAT"].ToString());
                        ObjCVarvwInvoices.mTaxTypeID = Convert.ToInt32(dr["TaxTypeID"].ToString());
                        ObjCVarvwInvoices.mTaxTypeName = Convert.ToString(dr["TaxTypeName"].ToString());
                        ObjCVarvwInvoices.mTaxPercentage = Convert.ToDecimal(dr["TaxPercentage"].ToString());
                        ObjCVarvwInvoices.mTaxAmount = Convert.ToDecimal(dr["TaxAmount"].ToString());
                        ObjCVarvwInvoices.mDiscountTypeID = Convert.ToInt32(dr["DiscountTypeID"].ToString());
                        ObjCVarvwInvoices.mDiscountTypeName = Convert.ToString(dr["DiscountTypeName"].ToString());
                        ObjCVarvwInvoices.mDiscountPercentage = Convert.ToDecimal(dr["DiscountPercentage"].ToString());
                        ObjCVarvwInvoices.mDiscountAmount = Convert.ToDecimal(dr["DiscountAmount"].ToString());
                        ObjCVarvwInvoices.mFixedDiscount = Convert.ToDecimal(dr["FixedDiscount"].ToString());
                        ObjCVarvwInvoices.mItems5PercTaxAmount = Convert.ToDecimal(dr["Items5PercTaxAmount"].ToString());
                        ObjCVarvwInvoices.mItems10PercTaxAmount = Convert.ToDecimal(dr["Items10PercTaxAmount"].ToString());
                        ObjCVarvwInvoices.mItems14PercTaxAmount = Convert.ToDecimal(dr["Items14PercTaxAmount"].ToString());
                        ObjCVarvwInvoices.mVATFromItems = Convert.ToDecimal(dr["VATFromItems"].ToString());
                        ObjCVarvwInvoices.mDiscountFromItems = Convert.ToDecimal(dr["DiscountFromItems"].ToString());
                        ObjCVarvwInvoices.mAmount = Convert.ToDecimal(dr["Amount"].ToString());
                        ObjCVarvwInvoices.mPaidAmount = Convert.ToDecimal(dr["PaidAmount"].ToString());
                        ObjCVarvwInvoices.mRemainingAmount = Convert.ToDecimal(dr["RemainingAmount"].ToString());
                        ObjCVarvwInvoices.mInvoiceDate = Convert.ToDateTime(dr["InvoiceDate"].ToString());
                        ObjCVarvwInvoices.mDueDate = Convert.ToDateTime(dr["DueDate"].ToString());
                        ObjCVarvwInvoices.mIsApproved = Convert.ToBoolean(dr["IsApproved"].ToString());
                        ObjCVarvwInvoices.mIsDeleted = Convert.ToBoolean(dr["IsDeleted"].ToString());
                        ObjCVarvwInvoices.mApprovingUserID = Convert.ToInt32(dr["ApprovingUserID"].ToString());
                        ObjCVarvwInvoices.mApprovingUserName = Convert.ToString(dr["ApprovingUserName"].ToString());
                        ObjCVarvwInvoices.mVesselID = Convert.ToInt32(dr["VesselID"].ToString());
                        ObjCVarvwInvoices.mVesselCode = Convert.ToString(dr["VesselCode"].ToString());
                        ObjCVarvwInvoices.mVesselName = Convert.ToString(dr["VesselName"].ToString());
                        ObjCVarvwInvoices.mLineID = Convert.ToInt32(dr["LineID"].ToString());
                        ObjCVarvwInvoices.mLineName = Convert.ToString(dr["LineName"].ToString());
                        ObjCVarvwInvoices.mVoyageOrTruckNumber = Convert.ToString(dr["VoyageOrTruckNumber"].ToString());
                        ObjCVarvwInvoices.mNumberOfAccNotes = Convert.ToInt32(dr["NumberOfAccNotes"].ToString());
                        ObjCVarvwInvoices.mNumberOfRoutings = Convert.ToInt32(dr["NumberOfRoutings"].ToString());
                        ObjCVarvwInvoices.mCreatorUserID = Convert.ToInt32(dr["CreatorUserID"].ToString());
                        ObjCVarvwInvoices.mCreatorName = Convert.ToString(dr["CreatorName"].ToString());
                        ObjCVarvwInvoices.mSalesmanID = Convert.ToInt32(dr["SalesmanID"].ToString());
                        ObjCVarvwInvoices.mSalesmanName = Convert.ToString(dr["SalesmanName"].ToString());
                        ObjCVarvwInvoices.mCreationDate = Convert.ToDateTime(dr["CreationDate"].ToString());
                        ObjCVarvwInvoices.mModificatorUserID = Convert.ToInt32(dr["ModificatorUserID"].ToString());
                        ObjCVarvwInvoices.mModificatorName = Convert.ToString(dr["ModificatorName"].ToString());
                        ObjCVarvwInvoices.mModificationDate = Convert.ToDateTime(dr["ModificationDate"].ToString());
                        ObjCVarvwInvoices.mLeftSignature = Convert.ToString(dr["LeftSignature"].ToString());
                        ObjCVarvwInvoices.mMiddleSignature = Convert.ToString(dr["MiddleSignature"].ToString());
                        ObjCVarvwInvoices.mRightSignature = Convert.ToString(dr["RightSignature"].ToString());
                        ObjCVarvwInvoices.mTaxAccount_ID = Convert.ToInt32(dr["TaxAccount_ID"].ToString());
                        ObjCVarvwInvoices.mTaxSubAccount_ID = Convert.ToInt32(dr["TaxSubAccount_ID"].ToString());
                        ObjCVarvwInvoices.mDiscAccount_ID = Convert.ToInt32(dr["DiscAccount_ID"].ToString());
                        ObjCVarvwInvoices.mDiscSubAccount_ID = Convert.ToInt32(dr["DiscSubAccount_ID"].ToString());
                        ObjCVarvwInvoices.mGRT = Convert.ToString(dr["GRT"].ToString());
                        ObjCVarvwInvoices.mDWT = Convert.ToString(dr["DWT"].ToString());
                        ObjCVarvwInvoices.mNRT = Convert.ToString(dr["NRT"].ToString());
                        ObjCVarvwInvoices.mLOA = Convert.ToString(dr["LOA"].ToString());
                        ObjCVarvwInvoices.mRoutingID = Convert.ToInt64(dr["RoutingID"].ToString());
                        ObjCVarvwInvoices.mCertificateNumber = Convert.ToString(dr["CertificateNumber"].ToString());
                        ObjCVarvwInvoices.mOperationContainersAndPackagesID = Convert.ToInt64(dr["OperationContainersAndPackagesID"].ToString());
                        ObjCVarvwInvoices.mTankOrFlexiNumber = Convert.ToString(dr["TankOrFlexiNumber"].ToString());
                        ObjCVarvwInvoices.mIsNeglectLimit = Convert.ToBoolean(dr["IsNeglectLimit"].ToString());
                        ObjCVarvwInvoices.mRelatedToInvoiceID = Convert.ToInt64(dr["RelatedToInvoiceID"].ToString());
                        ObjCVarvwInvoices.mRelatedToInvoiceNumber = Convert.ToInt64(dr["RelatedToInvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mRelatedToInvoiceTypeName = Convert.ToString(dr["RelatedToInvoiceTypeName"].ToString());
                        ObjCVarvwInvoices.mOperationOpenDate = Convert.ToDateTime(dr["OperationOpenDate"].ToString());
                        ObjCVarvwInvoices.mChildInvoiceID = Convert.ToInt64(dr["ChildInvoiceID"].ToString());
                        ObjCVarvwInvoices.mChildInvoiceNumber = Convert.ToInt64(dr["ChildInvoiceNumber"].ToString());
                        ObjCVarvwInvoices.mChildInvoiceTypeName = Convert.ToString(dr["ChildInvoiceTypeName"].ToString());
                        ObjCVarvwInvoices.mIsDraftApproved = Convert.ToBoolean(dr["IsDraftApproved"].ToString());
                        ObjCVarvwInvoices.mDraftApprovingUserID = Convert.ToInt32(dr["DraftApprovingUserID"].ToString());
                        ObjCVarvwInvoices.mPaymentDate = Convert.ToDateTime(dr["PaymentDate"].ToString());
                        ObjCVarvwInvoices.mTransactionTypeID = Convert.ToInt32(dr["TransactionTypeID"].ToString());
                        ObjCVarvwInvoices.mCutOffDate = Convert.ToDateTime(dr["CutOffDate"].ToString());
                        ObjCVarvwInvoices.mNotes = Convert.ToString(dr["Notes"].ToString());
                        ObjCVarvwInvoices.mEditableNotes = Convert.ToString(dr["EditableNotes"].ToString());
                        ObjCVarvwInvoices.mIs3PL = Convert.ToBoolean(dr["Is3PL"].ToString());
                        ObjCVarvwInvoices.mIsFleet = Convert.ToBoolean(dr["IsFleet"].ToString());
                        ObjCVarvwInvoices.mIsPrintOriginal = Convert.ToBoolean(dr["IsPrintOriginal"].ToString());
                        ObjCVarvwInvoices.mCancelledInvoiceID = Convert.ToInt64(dr["CancelledInvoiceID"].ToString());
                        ObjCVarvwInvoices.mIsDelivered = Convert.ToBoolean(dr["IsDelivered"].ToString());
                        ObjCVarvwInvoices.mManualPaymentStatusID = Convert.ToInt32(dr["ManualPaymentStatusID"].ToString());
                        ObjCVarvwInvoices.mManualPaymentStatusName = Convert.ToString(dr["ManualPaymentStatusName"].ToString());
                        ObjCVarvwInvoices.mECode = Convert.ToString(dr["ECode"].ToString());
                        TotRecs = Convert.ToInt32(dr["TotalRecords"].ToString());
                        lstCVarvwInvoices.Add(ObjCVarvwInvoices);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
    }
}
