using System;
using System.Text;
using System.Data;
using System.Collections;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;

/*This class is autogenerated by Khedrawy Code gen v.3.1*/
namespace Forwarding.MvcApp.Models.ContainerYard.Tariff
{
    [Serializable]
    public class CPKWH_MTY_Tariff_Details
    {
        #region "variables"
        private Int32 mID;
        #endregion

        #region "Methods"
        public Int32 ID
        {
            get { return mID; }
            set { mID = value; }
        }
        #endregion
    }
    [Serializable]
    public partial class CVarWH_MTY_Tariff_Details : CPKWH_MTY_Tariff_Details
    {
        #region "variables"
        internal Boolean mIsChanges = false;
        internal Int32 mChargeTypesID;
        internal Decimal mRate;
        internal Int32 mContainerTypesID;
        internal Int32 mWH_MTY_TariffID;
        internal Int32 mCalcTypesID;
        internal Boolean misCalcOneTimeToDay;
        #endregion

        #region "Methods"
        public Int32 ChargeTypesID
        {
            get { return mChargeTypesID; }
            set { mIsChanges = true; mChargeTypesID = value; }
        }
        public Decimal Rate
        {
            get { return mRate; }
            set { mIsChanges = true; mRate = value; }
        }
        public Int32 ContainerTypesID
        {
            get { return mContainerTypesID; }
            set { mIsChanges = true; mContainerTypesID = value; }
        }
        public Int32 WH_MTY_TariffID
        {
            get { return mWH_MTY_TariffID; }
            set { mIsChanges = true; mWH_MTY_TariffID = value; }
        }
        public Int32 CalcTypesID
        {
            get { return mCalcTypesID; }
            set { mIsChanges = true; mCalcTypesID = value; }
        }
        public Boolean isCalcOneTimeToDay
        {
            get { return misCalcOneTimeToDay; }
            set { mIsChanges = true; misCalcOneTimeToDay = value; }
        }
        #endregion

        #region Functions
        public Boolean GetIsChange()
        {
            return mIsChanges;
        }
        public void SetIsChange(Boolean IsChange)
        {
            mIsChanges = IsChange;
        }
        #endregion
    }

    public partial class CWH_MTY_Tariff_Details
    {
        #region "variables"
        /*If "App.Config" isnot exist add it to your Application
		Add this code after <Configuration> tag
		-------------------------------------------------------
		<appsettings>
		<add key="ConnectionString" value="............"/>
		</appsettings>
		-------------------------------------------------------
		where ".........." is connection string to database server*/
        private SqlTransaction tr;
        public List<CVarWH_MTY_Tariff_Details> lstCVarWH_MTY_Tariff_Details = new List<CVarWH_MTY_Tariff_Details>();
        public List<CPKWH_MTY_Tariff_Details> lstDeletedCPKWH_MTY_Tariff_Details = new List<CPKWH_MTY_Tariff_Details>();
        #endregion

        #region "Select Methods"
        public Exception GetList(string WhereClause)
        {
            return DataFill(WhereClause, true);
        }
        public Exception GetListPaging(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotalRecords)
        {
            return DataFill(PageSize, PageNumber, WhereClause, OrderBy, out TotalRecords);
        }
        public Exception GetItem(Int32 ID)
        {
            return DataFill(Convert.ToString(ID), false);
        }
        private Exception DataFill(string Param, Boolean IsList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarWH_MTY_Tariff_Details.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                if (IsList == true)
                {
                    Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                    Com.CommandText = "[dbo].GetListWH_MTY_Tariff_Details";
                    Com.Parameters[0].Value = Param;
                }
                else
                {
                    Com.CommandText = "[dbo].GetItemWH_MTY_Tariff_Details";
                    Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int));
                    Com.Parameters[0].Value = Convert.ToInt32(Param);
                }
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarWH_MTY_Tariff_Details ObjCVarWH_MTY_Tariff_Details = new CVarWH_MTY_Tariff_Details();
                        ObjCVarWH_MTY_Tariff_Details.ID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mChargeTypesID = Convert.ToInt32(dr["ChargeTypesID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mRate = Convert.ToDecimal(dr["Rate"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mContainerTypesID = Convert.ToInt32(dr["ContainerTypesID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mWH_MTY_TariffID = Convert.ToInt32(dr["WH_MTY_TariffID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mCalcTypesID = Convert.ToInt32(dr["CalcTypesID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.misCalcOneTimeToDay = Convert.ToBoolean(dr["isCalcOneTimeToDay"].ToString());
                        lstCVarWH_MTY_Tariff_Details.Add(ObjCVarWH_MTY_Tariff_Details);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        private Exception DataFill(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotRecs)
        {
            Exception Exp = null;
            TotRecs = 0;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarWH_MTY_Tariff_Details.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                Com.Parameters.Add(new SqlParameter("@PageSize", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@PageNumber", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                Com.Parameters.Add(new SqlParameter("@OrderBy", SqlDbType.VarChar));
                Com.CommandText = "[dbo].GetListPagingWH_MTY_Tariff_Details";
                Com.Parameters[0].Value = PageSize;
                Com.Parameters[1].Value = PageNumber;
                Com.Parameters[2].Value = WhereClause;
                Com.Parameters[3].Value = OrderBy;
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarWH_MTY_Tariff_Details ObjCVarWH_MTY_Tariff_Details = new CVarWH_MTY_Tariff_Details();
                        ObjCVarWH_MTY_Tariff_Details.ID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mChargeTypesID = Convert.ToInt32(dr["ChargeTypesID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mRate = Convert.ToDecimal(dr["Rate"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mContainerTypesID = Convert.ToInt32(dr["ContainerTypesID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mWH_MTY_TariffID = Convert.ToInt32(dr["WH_MTY_TariffID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.mCalcTypesID = Convert.ToInt32(dr["CalcTypesID"].ToString());
                        ObjCVarWH_MTY_Tariff_Details.misCalcOneTimeToDay = Convert.ToBoolean(dr["isCalcOneTimeToDay"].ToString());
                        TotRecs = Convert.ToInt32(dr["TotalRecords"].ToString());
                        lstCVarWH_MTY_Tariff_Details.Add(ObjCVarWH_MTY_Tariff_Details);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
        #region "Common Methods"
        private void BeginTrans(SqlCommand Com, SqlConnection Con)
        {

            tr = Con.BeginTransaction(IsolationLevel.Serializable);
            Com.CommandType = CommandType.StoredProcedure;
        }

        private void EndTrans(SqlCommand Com, SqlConnection Con)
        {

            Com.Transaction = tr;
            Com.Connection = Con;
            Com.ExecuteNonQuery();
            tr.Commit();
        }

        #endregion
        #region "Set List Method"
        private Exception SetList(string WhereClause, Boolean IsDelete)
        {

            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                if (IsDelete == true)
                    Com.CommandText = "[dbo].DeleteListWH_MTY_Tariff_Details";
                else
                    Com.CommandText = "[dbo].UpdateListWH_MTY_Tariff_Details";
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                BeginTrans(Com, Con);
                Com.Parameters[0].Value = WhereClause;
                EndTrans(Com, Con);
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
        #region "Delete Methods"
        public Exception DeleteItem(List<CPKWH_MTY_Tariff_Details> DeleteList)
        {

            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                Com.CommandText = "[dbo].DeleteItemWH_MTY_Tariff_Details";
                Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int));
                foreach (CPKWH_MTY_Tariff_Details ObjCPKWH_MTY_Tariff_Details in DeleteList)
                {
                    BeginTrans(Com, Con);
                    Com.Parameters[0].Value = Convert.ToInt32(ObjCPKWH_MTY_Tariff_Details.ID);
                    EndTrans(Com, Con);
                }
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
                DeleteList.Clear();
            }
            return Exp;
        }

        public Exception DeleteList(string WhereClause)
        {

            return SetList(WhereClause, true);
        }

        #endregion
        #region "Save Methods"
        public Exception SaveMethod(List<CVarWH_MTY_Tariff_Details> SaveList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                Com.Parameters.Add(new SqlParameter("@ChargeTypesID", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@Rate", SqlDbType.Decimal));
                Com.Parameters.Add(new SqlParameter("@ContainerTypesID", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@WH_MTY_TariffID", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@CalcTypesID", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@isCalcOneTimeToDay", SqlDbType.Bit));
                SqlParameter paraID = Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, "ID", DataRowVersion.Default, null));
                foreach (CVarWH_MTY_Tariff_Details ObjCVarWH_MTY_Tariff_Details in SaveList)
                {
                    if (ObjCVarWH_MTY_Tariff_Details.mIsChanges == true)
                    {
                        if (ObjCVarWH_MTY_Tariff_Details.ID == 0)
                        {
                            Com.CommandText = "[dbo].InsertItemWH_MTY_Tariff_Details";
                            paraID.Direction = ParameterDirection.Output;
                        }
                        else if (ObjCVarWH_MTY_Tariff_Details.ID != 0)
                        {
                            Com.CommandText = "[dbo].UpdateItemWH_MTY_Tariff_Details";
                            paraID.Direction = ParameterDirection.Input;
                        }
                        BeginTrans(Com, Con);
                        if (ObjCVarWH_MTY_Tariff_Details.ID != 0)
                        {
                            Com.Parameters["@ID"].Value = ObjCVarWH_MTY_Tariff_Details.ID;
                        }
                        Com.Parameters["@ChargeTypesID"].Value = ObjCVarWH_MTY_Tariff_Details.ChargeTypesID;
                        Com.Parameters["@Rate"].Value = ObjCVarWH_MTY_Tariff_Details.Rate;
                        Com.Parameters["@ContainerTypesID"].Value = ObjCVarWH_MTY_Tariff_Details.ContainerTypesID;
                        Com.Parameters["@WH_MTY_TariffID"].Value = ObjCVarWH_MTY_Tariff_Details.WH_MTY_TariffID;
                        Com.Parameters["@CalcTypesID"].Value = ObjCVarWH_MTY_Tariff_Details.CalcTypesID;
                        Com.Parameters["@isCalcOneTimeToDay"].Value = ObjCVarWH_MTY_Tariff_Details.isCalcOneTimeToDay;
                        EndTrans(Com, Con);
                        if (ObjCVarWH_MTY_Tariff_Details.ID == 0)
                        {
                            ObjCVarWH_MTY_Tariff_Details.ID = Convert.ToInt32(Com.Parameters["@ID"].Value);
                        }
                        ObjCVarWH_MTY_Tariff_Details.mIsChanges = false;
                    }
                }
            }
            catch (Exception ex)
            {
                Exp = ex;
                if (tr != null)
                    tr.Rollback();
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }
        #endregion
        #region "Update Methods"
        public Exception UpdateList(string UpdateClause)
        {

            return SetList(UpdateClause, false);
        }

        #endregion
    }
}

