using System;
using System.Text;
using System.Data;
using System.Collections;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;

/*This class is autogenerated by Khedrawy Code gen v.3.1*/
namespace Forwarding.MvcApp.Models.DynamicsCRM
{
    [Serializable]
    public partial class CVarvwcrmChargeTypes
    {
        #region "variables"
        internal Boolean mIsChanges = false;
        internal Int32 mID;
        internal String mCode;
        internal String mName;
        internal String mLocalName;
        internal Int32 mMeasurementID;
        internal Int32 mTaxeTypeID;
        internal Int32 mInvoiceTypeID;
        internal Int32 mViewOrder;
        internal String mNotes;
        internal Boolean mIsUsedInReceivable;
        internal Boolean mIsUsedInPayable;
        internal Boolean mIsOcean;
        internal Boolean mIsInland;
        internal Boolean mIsAir;
        internal Boolean mIsDefaultInQuotation;
        internal Boolean mIsDefaultInOperations;
        internal Boolean mIsAddedManually;
        internal Boolean mIsInactive;
        internal Int32 mCreatorUserID;
        internal DateTime mCreationDate;
        internal Int32 mModificatorUserID;
        internal DateTime mModificationDate;
        internal Int32 mLockingUserID;
        internal DateTime mTimeLocked;
        internal Boolean mIsOperationChargeType;
        internal Boolean mIsGeneralChargeType;
        internal Int32 mAccountID_Revenue;
        internal Int32 mSubAccountID_Revenue;
        internal Int32 mCostCenterID_Revenue;
        internal Int32 mAccountID_Expense;
        internal Int32 mSubAccountID_Expense;
        internal Int32 mCostCenterID_Expense;
        internal Int32 mTemplateID;
        internal Int64 mPurchaseItemID;
        internal Boolean mIsTank;
        internal Boolean mIsWarehouseChargeType;
        internal Boolean mIsExcludeInTruckingOrderPrint;
        internal Int32 mAccountID_Return;
        internal Int32 mSubAccountID_Return;
        internal Boolean mIsOfficial;
        internal String mPreCode;
        internal Int32 mChargeTypeGroupID;
        internal Decimal mCost;
        internal String mcrmID;
        internal String mForwardingTableName;
        internal String mcrmTableName;
        #endregion

        #region "Methods"
        public Int32 ID
        {
            get { return mID; }
            set { mID = value; }
        }
        public String Code
        {
            get { return mCode; }
            set { mCode = value; }
        }
        public String Name
        {
            get { return mName; }
            set { mName = value; }
        }
        public String LocalName
        {
            get { return mLocalName; }
            set { mLocalName = value; }
        }
        public Int32 MeasurementID
        {
            get { return mMeasurementID; }
            set { mMeasurementID = value; }
        }
        public Int32 TaxeTypeID
        {
            get { return mTaxeTypeID; }
            set { mTaxeTypeID = value; }
        }
        public Int32 InvoiceTypeID
        {
            get { return mInvoiceTypeID; }
            set { mInvoiceTypeID = value; }
        }
        public Int32 ViewOrder
        {
            get { return mViewOrder; }
            set { mViewOrder = value; }
        }
        public String Notes
        {
            get { return mNotes; }
            set { mNotes = value; }
        }
        public Boolean IsUsedInReceivable
        {
            get { return mIsUsedInReceivable; }
            set { mIsUsedInReceivable = value; }
        }
        public Boolean IsUsedInPayable
        {
            get { return mIsUsedInPayable; }
            set { mIsUsedInPayable = value; }
        }
        public Boolean IsOcean
        {
            get { return mIsOcean; }
            set { mIsOcean = value; }
        }
        public Boolean IsInland
        {
            get { return mIsInland; }
            set { mIsInland = value; }
        }
        public Boolean IsAir
        {
            get { return mIsAir; }
            set { mIsAir = value; }
        }
        public Boolean IsDefaultInQuotation
        {
            get { return mIsDefaultInQuotation; }
            set { mIsDefaultInQuotation = value; }
        }
        public Boolean IsDefaultInOperations
        {
            get { return mIsDefaultInOperations; }
            set { mIsDefaultInOperations = value; }
        }
        public Boolean IsAddedManually
        {
            get { return mIsAddedManually; }
            set { mIsAddedManually = value; }
        }
        public Boolean IsInactive
        {
            get { return mIsInactive; }
            set { mIsInactive = value; }
        }
        public Int32 CreatorUserID
        {
            get { return mCreatorUserID; }
            set { mCreatorUserID = value; }
        }
        public DateTime CreationDate
        {
            get { return mCreationDate; }
            set { mCreationDate = value; }
        }
        public Int32 ModificatorUserID
        {
            get { return mModificatorUserID; }
            set { mModificatorUserID = value; }
        }
        public DateTime ModificationDate
        {
            get { return mModificationDate; }
            set { mModificationDate = value; }
        }
        public Int32 LockingUserID
        {
            get { return mLockingUserID; }
            set { mLockingUserID = value; }
        }
        public DateTime TimeLocked
        {
            get { return mTimeLocked; }
            set { mTimeLocked = value; }
        }
        public Boolean IsOperationChargeType
        {
            get { return mIsOperationChargeType; }
            set { mIsOperationChargeType = value; }
        }
        public Boolean IsGeneralChargeType
        {
            get { return mIsGeneralChargeType; }
            set { mIsGeneralChargeType = value; }
        }
        public Int32 AccountID_Revenue
        {
            get { return mAccountID_Revenue; }
            set { mAccountID_Revenue = value; }
        }
        public Int32 SubAccountID_Revenue
        {
            get { return mSubAccountID_Revenue; }
            set { mSubAccountID_Revenue = value; }
        }
        public Int32 CostCenterID_Revenue
        {
            get { return mCostCenterID_Revenue; }
            set { mCostCenterID_Revenue = value; }
        }
        public Int32 AccountID_Expense
        {
            get { return mAccountID_Expense; }
            set { mAccountID_Expense = value; }
        }
        public Int32 SubAccountID_Expense
        {
            get { return mSubAccountID_Expense; }
            set { mSubAccountID_Expense = value; }
        }
        public Int32 CostCenterID_Expense
        {
            get { return mCostCenterID_Expense; }
            set { mCostCenterID_Expense = value; }
        }
        public Int32 TemplateID
        {
            get { return mTemplateID; }
            set { mTemplateID = value; }
        }
        public Int64 PurchaseItemID
        {
            get { return mPurchaseItemID; }
            set { mPurchaseItemID = value; }
        }
        public Boolean IsTank
        {
            get { return mIsTank; }
            set { mIsTank = value; }
        }
        public Boolean IsWarehouseChargeType
        {
            get { return mIsWarehouseChargeType; }
            set { mIsWarehouseChargeType = value; }
        }
        public Boolean IsExcludeInTruckingOrderPrint
        {
            get { return mIsExcludeInTruckingOrderPrint; }
            set { mIsExcludeInTruckingOrderPrint = value; }
        }
        public Int32 AccountID_Return
        {
            get { return mAccountID_Return; }
            set { mAccountID_Return = value; }
        }
        public Int32 SubAccountID_Return
        {
            get { return mSubAccountID_Return; }
            set { mSubAccountID_Return = value; }
        }
        public Boolean IsOfficial
        {
            get { return mIsOfficial; }
            set { mIsOfficial = value; }
        }
        public String PreCode
        {
            get { return mPreCode; }
            set { mPreCode = value; }
        }
        public Int32 ChargeTypeGroupID
        {
            get { return mChargeTypeGroupID; }
            set { mChargeTypeGroupID = value; }
        }
        public Decimal Cost
        {
            get { return mCost; }
            set { mCost = value; }
        }
        public String crmID
        {
            get { return mcrmID; }
            set { mcrmID = value; }
        }
        public String ForwardingTableName
        {
            get { return mForwardingTableName; }
            set { mForwardingTableName = value; }
        }
        public String crmTableName
        {
            get { return mcrmTableName; }
            set { mcrmTableName = value; }
        }
        #endregion
    }

    public partial class CvwcrmChargeTypes
    {
        #region "variables"
        /*If "App.Config" isnot exist add it to your Application
		Add this code after <Configuration> tag
		-------------------------------------------------------
		<appsettings>
		<add key="ConnectionString" value="............"/>
		</appsettings>
		-------------------------------------------------------
		where ".........." is connection string to database server*/
        private SqlTransaction tr;
        public List<CVarvwcrmChargeTypes> lstCVarvwcrmChargeTypes = new List<CVarvwcrmChargeTypes>();
        #endregion

        #region "Select Methods"
        public Exception GetList(string WhereClause)
        {
            return DataFill(WhereClause, true);
        }
        public Exception GetListPaging(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotalRecords)
        {
            return DataFill(PageSize, PageNumber, WhereClause, OrderBy, out TotalRecords);
        }
        private Exception DataFill(string Param, Boolean IsList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarvwcrmChargeTypes.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                if (IsList == true)
                {
                    Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                    Com.CommandText = "[dbo].GetListvwcrmChargeTypes";
                    Com.Parameters[0].Value = Param;
                }
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarvwcrmChargeTypes ObjCVarvwcrmChargeTypes = new CVarvwcrmChargeTypes();
                        ObjCVarvwcrmChargeTypes.mID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarvwcrmChargeTypes.mCode = Convert.ToString(dr["Code"].ToString());
                        ObjCVarvwcrmChargeTypes.mName = Convert.ToString(dr["Name"].ToString());
                        ObjCVarvwcrmChargeTypes.mLocalName = Convert.ToString(dr["LocalName"].ToString());
                        ObjCVarvwcrmChargeTypes.mMeasurementID = Convert.ToInt32(dr["MeasurementID"].ToString());
                        ObjCVarvwcrmChargeTypes.mTaxeTypeID = Convert.ToInt32(dr["TaxeTypeID"].ToString());
                        ObjCVarvwcrmChargeTypes.mInvoiceTypeID = Convert.ToInt32(dr["InvoiceTypeID"].ToString());
                        ObjCVarvwcrmChargeTypes.mViewOrder = Convert.ToInt32(dr["ViewOrder"].ToString());
                        ObjCVarvwcrmChargeTypes.mNotes = Convert.ToString(dr["Notes"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsUsedInReceivable = Convert.ToBoolean(dr["IsUsedInReceivable"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsUsedInPayable = Convert.ToBoolean(dr["IsUsedInPayable"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsOcean = Convert.ToBoolean(dr["IsOcean"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsInland = Convert.ToBoolean(dr["IsInland"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsAir = Convert.ToBoolean(dr["IsAir"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsDefaultInQuotation = Convert.ToBoolean(dr["IsDefaultInQuotation"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsDefaultInOperations = Convert.ToBoolean(dr["IsDefaultInOperations"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsAddedManually = Convert.ToBoolean(dr["IsAddedManually"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsInactive = Convert.ToBoolean(dr["IsInactive"].ToString());
                        ObjCVarvwcrmChargeTypes.mCreatorUserID = Convert.ToInt32(dr["CreatorUserID"].ToString());
                        ObjCVarvwcrmChargeTypes.mCreationDate = Convert.ToDateTime(dr["CreationDate"].ToString());
                        ObjCVarvwcrmChargeTypes.mModificatorUserID = Convert.ToInt32(dr["ModificatorUserID"].ToString());
                        ObjCVarvwcrmChargeTypes.mModificationDate = Convert.ToDateTime(dr["ModificationDate"].ToString());
                        ObjCVarvwcrmChargeTypes.mLockingUserID = Convert.ToInt32(dr["LockingUserID"].ToString());
                        ObjCVarvwcrmChargeTypes.mTimeLocked = Convert.ToDateTime(dr["TimeLocked"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsOperationChargeType = Convert.ToBoolean(dr["IsOperationChargeType"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsGeneralChargeType = Convert.ToBoolean(dr["IsGeneralChargeType"].ToString());
                        ObjCVarvwcrmChargeTypes.mAccountID_Revenue = Convert.ToInt32(dr["AccountID_Revenue"].ToString());
                        ObjCVarvwcrmChargeTypes.mSubAccountID_Revenue = Convert.ToInt32(dr["SubAccountID_Revenue"].ToString());
                        ObjCVarvwcrmChargeTypes.mCostCenterID_Revenue = Convert.ToInt32(dr["CostCenterID_Revenue"].ToString());
                        ObjCVarvwcrmChargeTypes.mAccountID_Expense = Convert.ToInt32(dr["AccountID_Expense"].ToString());
                        ObjCVarvwcrmChargeTypes.mSubAccountID_Expense = Convert.ToInt32(dr["SubAccountID_Expense"].ToString());
                        ObjCVarvwcrmChargeTypes.mCostCenterID_Expense = Convert.ToInt32(dr["CostCenterID_Expense"].ToString());
                        ObjCVarvwcrmChargeTypes.mTemplateID = Convert.ToInt32(dr["TemplateID"].ToString());
                        ObjCVarvwcrmChargeTypes.mPurchaseItemID = Convert.ToInt64(dr["PurchaseItemID"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsTank = Convert.ToBoolean(dr["IsTank"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsWarehouseChargeType = Convert.ToBoolean(dr["IsWarehouseChargeType"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsExcludeInTruckingOrderPrint = Convert.ToBoolean(dr["IsExcludeInTruckingOrderPrint"].ToString());
                        ObjCVarvwcrmChargeTypes.mAccountID_Return = Convert.ToInt32(dr["AccountID_Return"].ToString());
                        ObjCVarvwcrmChargeTypes.mSubAccountID_Return = Convert.ToInt32(dr["SubAccountID_Return"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsOfficial = Convert.ToBoolean(dr["IsOfficial"].ToString());
                        ObjCVarvwcrmChargeTypes.mPreCode = Convert.ToString(dr["PreCode"].ToString());
                        ObjCVarvwcrmChargeTypes.mChargeTypeGroupID = Convert.ToInt32(dr["ChargeTypeGroupID"].ToString());
                        ObjCVarvwcrmChargeTypes.mCost = Convert.ToDecimal(dr["Cost"].ToString());
                        ObjCVarvwcrmChargeTypes.mcrmID = Convert.ToString(dr["crmID"].ToString());
                        ObjCVarvwcrmChargeTypes.mForwardingTableName = Convert.ToString(dr["ForwardingTableName"].ToString());
                        ObjCVarvwcrmChargeTypes.mcrmTableName = Convert.ToString(dr["crmTableName"].ToString());
                        lstCVarvwcrmChargeTypes.Add(ObjCVarvwcrmChargeTypes);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        private Exception DataFill(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotRecs)
        {
            Exception Exp = null;
            TotRecs = 0;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarvwcrmChargeTypes.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                Com.Parameters.Add(new SqlParameter("@PageSize", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@PageNumber", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                Com.Parameters.Add(new SqlParameter("@OrderBy", SqlDbType.VarChar));
                Com.CommandText = "[dbo].GetListPagingvwcrmChargeTypes";
                Com.Parameters[0].Value = PageSize;
                Com.Parameters[1].Value = PageNumber;
                Com.Parameters[2].Value = WhereClause;
                Com.Parameters[3].Value = OrderBy;
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarvwcrmChargeTypes ObjCVarvwcrmChargeTypes = new CVarvwcrmChargeTypes();
                        ObjCVarvwcrmChargeTypes.mID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarvwcrmChargeTypes.mCode = Convert.ToString(dr["Code"].ToString());
                        ObjCVarvwcrmChargeTypes.mName = Convert.ToString(dr["Name"].ToString());
                        ObjCVarvwcrmChargeTypes.mLocalName = Convert.ToString(dr["LocalName"].ToString());
                        ObjCVarvwcrmChargeTypes.mMeasurementID = Convert.ToInt32(dr["MeasurementID"].ToString());
                        ObjCVarvwcrmChargeTypes.mTaxeTypeID = Convert.ToInt32(dr["TaxeTypeID"].ToString());
                        ObjCVarvwcrmChargeTypes.mInvoiceTypeID = Convert.ToInt32(dr["InvoiceTypeID"].ToString());
                        ObjCVarvwcrmChargeTypes.mViewOrder = Convert.ToInt32(dr["ViewOrder"].ToString());
                        ObjCVarvwcrmChargeTypes.mNotes = Convert.ToString(dr["Notes"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsUsedInReceivable = Convert.ToBoolean(dr["IsUsedInReceivable"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsUsedInPayable = Convert.ToBoolean(dr["IsUsedInPayable"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsOcean = Convert.ToBoolean(dr["IsOcean"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsInland = Convert.ToBoolean(dr["IsInland"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsAir = Convert.ToBoolean(dr["IsAir"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsDefaultInQuotation = Convert.ToBoolean(dr["IsDefaultInQuotation"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsDefaultInOperations = Convert.ToBoolean(dr["IsDefaultInOperations"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsAddedManually = Convert.ToBoolean(dr["IsAddedManually"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsInactive = Convert.ToBoolean(dr["IsInactive"].ToString());
                        ObjCVarvwcrmChargeTypes.mCreatorUserID = Convert.ToInt32(dr["CreatorUserID"].ToString());
                        ObjCVarvwcrmChargeTypes.mCreationDate = Convert.ToDateTime(dr["CreationDate"].ToString());
                        ObjCVarvwcrmChargeTypes.mModificatorUserID = Convert.ToInt32(dr["ModificatorUserID"].ToString());
                        ObjCVarvwcrmChargeTypes.mModificationDate = Convert.ToDateTime(dr["ModificationDate"].ToString());
                        ObjCVarvwcrmChargeTypes.mLockingUserID = Convert.ToInt32(dr["LockingUserID"].ToString());
                        ObjCVarvwcrmChargeTypes.mTimeLocked = Convert.ToDateTime(dr["TimeLocked"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsOperationChargeType = Convert.ToBoolean(dr["IsOperationChargeType"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsGeneralChargeType = Convert.ToBoolean(dr["IsGeneralChargeType"].ToString());
                        ObjCVarvwcrmChargeTypes.mAccountID_Revenue = Convert.ToInt32(dr["AccountID_Revenue"].ToString());
                        ObjCVarvwcrmChargeTypes.mSubAccountID_Revenue = Convert.ToInt32(dr["SubAccountID_Revenue"].ToString());
                        ObjCVarvwcrmChargeTypes.mCostCenterID_Revenue = Convert.ToInt32(dr["CostCenterID_Revenue"].ToString());
                        ObjCVarvwcrmChargeTypes.mAccountID_Expense = Convert.ToInt32(dr["AccountID_Expense"].ToString());
                        ObjCVarvwcrmChargeTypes.mSubAccountID_Expense = Convert.ToInt32(dr["SubAccountID_Expense"].ToString());
                        ObjCVarvwcrmChargeTypes.mCostCenterID_Expense = Convert.ToInt32(dr["CostCenterID_Expense"].ToString());
                        ObjCVarvwcrmChargeTypes.mTemplateID = Convert.ToInt32(dr["TemplateID"].ToString());
                        ObjCVarvwcrmChargeTypes.mPurchaseItemID = Convert.ToInt64(dr["PurchaseItemID"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsTank = Convert.ToBoolean(dr["IsTank"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsWarehouseChargeType = Convert.ToBoolean(dr["IsWarehouseChargeType"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsExcludeInTruckingOrderPrint = Convert.ToBoolean(dr["IsExcludeInTruckingOrderPrint"].ToString());
                        ObjCVarvwcrmChargeTypes.mAccountID_Return = Convert.ToInt32(dr["AccountID_Return"].ToString());
                        ObjCVarvwcrmChargeTypes.mSubAccountID_Return = Convert.ToInt32(dr["SubAccountID_Return"].ToString());
                        ObjCVarvwcrmChargeTypes.mIsOfficial = Convert.ToBoolean(dr["IsOfficial"].ToString());
                        ObjCVarvwcrmChargeTypes.mPreCode = Convert.ToString(dr["PreCode"].ToString());
                        ObjCVarvwcrmChargeTypes.mChargeTypeGroupID = Convert.ToInt32(dr["ChargeTypeGroupID"].ToString());
                        ObjCVarvwcrmChargeTypes.mCost = Convert.ToDecimal(dr["Cost"].ToString());
                        ObjCVarvwcrmChargeTypes.mcrmID = Convert.ToString(dr["crmID"].ToString());
                        ObjCVarvwcrmChargeTypes.mForwardingTableName = Convert.ToString(dr["ForwardingTableName"].ToString());
                        ObjCVarvwcrmChargeTypes.mcrmTableName = Convert.ToString(dr["crmTableName"].ToString());
                        TotRecs = Convert.ToInt32(dr["TotalRecords"].ToString());
                        lstCVarvwcrmChargeTypes.Add(ObjCVarvwcrmChargeTypes);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
    }
}
