using System;
using System.Text;
using System.Data;
using System.Collections;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;

/*This class is autogenerated by Khedrawy Code gen v.3.1*/
namespace Forwarding.MvcApp.Models.ContainerFreightStation.Tariff
{
    [Serializable]
    public class CPKWH_FCL_Tariff_Imo
    {
        #region "variables"
        private Int32 mID;
        #endregion

        #region "Methods"
        public Int32 ID
        {
            get { return mID; }
            set { mID = value; }
        }
        #endregion
    }
    [Serializable]
    public partial class CVarWH_FCL_Tariff_Imo : CPKWH_FCL_Tariff_Imo
    {
        #region "variables"
        internal Boolean mIsChanges = false;
        internal Int32 mWH_FCL_TariffID;
        internal Int32 mImoClassNo;
        internal Decimal mImoRate;
        internal Int32 mCalculatedBy;
        #endregion

        #region "Methods"
        public Int32 WH_FCL_TariffID
        {
            get { return mWH_FCL_TariffID; }
            set { mIsChanges = true; mWH_FCL_TariffID = value; }
        }
        public Int32 ImoClassNo
        {
            get { return mImoClassNo; }
            set { mIsChanges = true; mImoClassNo = value; }
        }
        public Decimal ImoRate
        {
            get { return mImoRate; }
            set { mIsChanges = true; mImoRate = value; }
        }
        public Int32 CalculatedBy
        {
            get { return mCalculatedBy; }
            set { mIsChanges = true; mCalculatedBy = value; }
        }
        #endregion

        #region Functions
        public Boolean GetIsChange()
        {
            return mIsChanges;
        }
        public void SetIsChange(Boolean IsChange)
        {
            mIsChanges = IsChange;
        }
        #endregion
    }

    public partial class CWH_FCL_Tariff_Imo
    {
        #region "variables"
        /*If "App.Config" isnot exist add it to your Application
		Add this code after <Configuration> tag
		-------------------------------------------------------
		<appsettings>
		<add key="ConnectionString" value="............"/>
		</appsettings>
		-------------------------------------------------------
		where ".........." is connection string to database server*/
        private SqlTransaction tr;
        public List<CVarWH_FCL_Tariff_Imo> lstCVarWH_FCL_Tariff_Imo = new List<CVarWH_FCL_Tariff_Imo>();
        public List<CPKWH_FCL_Tariff_Imo> lstDeletedCPKWH_FCL_Tariff_Imo = new List<CPKWH_FCL_Tariff_Imo>();
        #endregion

        #region "Select Methods"
        public Exception GetList(string WhereClause)
        {
            return DataFill(WhereClause, true);
        }
        public Exception GetListPaging(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotalRecords)
        {
            return DataFill(PageSize, PageNumber, WhereClause, OrderBy, out TotalRecords);
        }
        public Exception GetItem(Int32 ID)
        {
            return DataFill(Convert.ToString(ID), false);
        }
        private Exception DataFill(string Param, Boolean IsList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarWH_FCL_Tariff_Imo.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                if (IsList == true)
                {
                    Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                    Com.CommandText = "[dbo].GetListWH_FCL_Tariff_Imo";
                    Com.Parameters[0].Value = Param;
                }
                else
                {
                    Com.CommandText = "[dbo].GetItemWH_FCL_Tariff_Imo";
                    Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int));
                    Com.Parameters[0].Value = Convert.ToInt32(Param);
                }
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarWH_FCL_Tariff_Imo ObjCVarWH_FCL_Tariff_Imo = new CVarWH_FCL_Tariff_Imo();
                        ObjCVarWH_FCL_Tariff_Imo.ID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mWH_FCL_TariffID = Convert.ToInt32(dr["WH_FCL_TariffID"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mImoClassNo = Convert.ToInt32(dr["ImoClassNo"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mImoRate = Convert.ToDecimal(dr["ImoRate"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mCalculatedBy = Convert.ToInt32(dr["CalculatedBy"].ToString());
                        lstCVarWH_FCL_Tariff_Imo.Add(ObjCVarWH_FCL_Tariff_Imo);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        private Exception DataFill(Int32 PageSize, Int32 PageNumber, string WhereClause, string OrderBy, out Int32 TotRecs)
        {
            Exception Exp = null;
            TotRecs = 0;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            SqlDataReader dr;
            lstCVarWH_FCL_Tariff_Imo.Clear();

            try
            {
                Con.Open();
                tr = Con.BeginTransaction(IsolationLevel.ReadCommitted);
                Com = new SqlCommand();
                Com.CommandType = CommandType.StoredProcedure;
                Com.Parameters.Add(new SqlParameter("@PageSize", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@PageNumber", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                Com.Parameters.Add(new SqlParameter("@OrderBy", SqlDbType.VarChar));
                Com.CommandText = "[dbo].GetListPagingWH_FCL_Tariff_Imo";
                Com.Parameters[0].Value = PageSize;
                Com.Parameters[1].Value = PageNumber;
                Com.Parameters[2].Value = WhereClause;
                Com.Parameters[3].Value = OrderBy;
                Com.Transaction = tr;
                Com.Connection = Con;
                dr = Com.ExecuteReader();
                try
                {
                    while (dr.Read())
                    {
                        /*Start DataReader*/
                        CVarWH_FCL_Tariff_Imo ObjCVarWH_FCL_Tariff_Imo = new CVarWH_FCL_Tariff_Imo();
                        ObjCVarWH_FCL_Tariff_Imo.ID = Convert.ToInt32(dr["ID"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mWH_FCL_TariffID = Convert.ToInt32(dr["WH_FCL_TariffID"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mImoClassNo = Convert.ToInt32(dr["ImoClassNo"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mImoRate = Convert.ToDecimal(dr["ImoRate"].ToString());
                        ObjCVarWH_FCL_Tariff_Imo.mCalculatedBy = Convert.ToInt32(dr["CalculatedBy"].ToString());
                        TotRecs = Convert.ToInt32(dr["TotalRecords"].ToString());
                        lstCVarWH_FCL_Tariff_Imo.Add(ObjCVarWH_FCL_Tariff_Imo);
                    }
                }
                catch (Exception ex)
                {
                    Exp = ex;
                }
                finally
                {
                    if (dr != null)
                    {
                        dr.Close();
                        dr.Dispose();
                    }
                }
                tr.Commit();
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
        #region "Common Methods"
        private void BeginTrans(SqlCommand Com, SqlConnection Con)
        {

            tr = Con.BeginTransaction(IsolationLevel.Serializable);
            Com.CommandType = CommandType.StoredProcedure;
        }

        private void EndTrans(SqlCommand Com, SqlConnection Con)
        {

            Com.Transaction = tr;
            Com.Connection = Con;
            Com.ExecuteNonQuery();
            tr.Commit();
        }

        #endregion
        #region "Set List Method"
        private Exception SetList(string WhereClause, Boolean IsDelete)
        {

            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                if (IsDelete == true)
                    Com.CommandText = "[dbo].DeleteListWH_FCL_Tariff_Imo";
                else
                    Com.CommandText = "[dbo].UpdateListWH_FCL_Tariff_Imo";
                Com.Parameters.Add(new SqlParameter("@WhereClause", SqlDbType.NVarChar));
                BeginTrans(Com, Con);
                Com.Parameters[0].Value = WhereClause;
                EndTrans(Com, Con);
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }

        #endregion
        #region "Delete Methods"
        public Exception DeleteItem(List<CPKWH_FCL_Tariff_Imo> DeleteList)
        {

            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                Com.CommandText = "[dbo].DeleteItemWH_FCL_Tariff_Imo";
                Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int));
                foreach (CPKWH_FCL_Tariff_Imo ObjCPKWH_FCL_Tariff_Imo in DeleteList)
                {
                    BeginTrans(Com, Con);
                    Com.Parameters[0].Value = Convert.ToInt32(ObjCPKWH_FCL_Tariff_Imo.ID);
                    EndTrans(Com, Con);
                }
            }
            catch (Exception ex)
            {
                Exp = ex;
            }
            finally
            {
                Con.Close();
                Con.Dispose();
                DeleteList.Clear();
            }
            return Exp;
        }

        public Exception DeleteList(string WhereClause)
        {

            return SetList(WhereClause, true);
        }

        #endregion
        #region "Save Methods"
        public Exception SaveMethod(List<CVarWH_FCL_Tariff_Imo> SaveList)
        {
            Exception Exp = null;
            SqlConnection Con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ToString());
            SqlCommand Com;
            try
            {
                Con.Open();
                Com = new SqlCommand();
                Com.Parameters.Add(new SqlParameter("@WH_FCL_TariffID", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@ImoClassNo", SqlDbType.Int));
                Com.Parameters.Add(new SqlParameter("@ImoRate", SqlDbType.Decimal));
                Com.Parameters.Add(new SqlParameter("@CalculatedBy", SqlDbType.Int));
                SqlParameter paraID = Com.Parameters.Add(new SqlParameter("@ID", SqlDbType.Int, 0, ParameterDirection.Input, false, 0, 0, "ID", DataRowVersion.Default, null));
                foreach (CVarWH_FCL_Tariff_Imo ObjCVarWH_FCL_Tariff_Imo in SaveList)
                {
                    if (ObjCVarWH_FCL_Tariff_Imo.mIsChanges == true)
                    {
                        if (ObjCVarWH_FCL_Tariff_Imo.ID == 0)
                        {
                            Com.CommandText = "[dbo].InsertItemWH_FCL_Tariff_Imo";
                            paraID.Direction = ParameterDirection.Output;
                        }
                        else if (ObjCVarWH_FCL_Tariff_Imo.ID != 0)
                        {
                            Com.CommandText = "[dbo].UpdateItemWH_FCL_Tariff_Imo";
                            paraID.Direction = ParameterDirection.Input;
                        }
                        BeginTrans(Com, Con);
                        if (ObjCVarWH_FCL_Tariff_Imo.ID != 0)
                        {
                            Com.Parameters["@ID"].Value = ObjCVarWH_FCL_Tariff_Imo.ID;
                        }
                        Com.Parameters["@WH_FCL_TariffID"].Value = ObjCVarWH_FCL_Tariff_Imo.WH_FCL_TariffID;
                        Com.Parameters["@ImoClassNo"].Value = ObjCVarWH_FCL_Tariff_Imo.ImoClassNo;
                        Com.Parameters["@ImoRate"].Value = ObjCVarWH_FCL_Tariff_Imo.ImoRate;
                        Com.Parameters["@CalculatedBy"].Value = ObjCVarWH_FCL_Tariff_Imo.CalculatedBy;
                        EndTrans(Com, Con);
                        if (ObjCVarWH_FCL_Tariff_Imo.ID == 0)
                        {
                            ObjCVarWH_FCL_Tariff_Imo.ID = Convert.ToInt32(Com.Parameters["@ID"].Value);
                        }
                        ObjCVarWH_FCL_Tariff_Imo.mIsChanges = false;
                    }
                }
            }
            catch (Exception ex)
            {
                Exp = ex;
                if (tr != null)
                    tr.Rollback();
            }
            finally
            {
                Con.Close();
                Con.Dispose();
            }
            return Exp;
        }
        #endregion
        #region "Update Methods"
        public Exception UpdateList(string UpdateClause)
        {

            return SetList(UpdateClause, false);
        }

        #endregion
    }
}
